language: ruby

rvm:
  - 1.9.3-p547

go:
  - 1.3

before_install:
  - git submodule update --init --recursive
  - ./scripts/travis/install_spiff
  - export PATH=$PATH:$PWD
script:
  - bundle exec rspec spec
  - rm spiff
  - bundle exec bosh -n sync blobs
  - ./scripts/unused_blobs
