---
debian_nfs_server/nfs-kernel-server_1%3a1.2.0-4ubuntu4.1_amd64.deb:
  object_id: rest/objects/4e4e78bca41e122204e4e9863d076304f307136db190
  sha: a44b3f8319984bace61f21bb6d15cee1419e5bf3
  size: 169618
uaa/cloudfoundry-identity-varz-1.0.2.war:
  object_id: rest/objects/4e4e78bca21e121204e4e86ee151bc050928ba58f527
  sha: 8c35ed35fb6dfc4a97a243447763c635812066e8
  size: 5727747
nginx/headers-more-v0.25.tgz:
  object_id: a621718d-df24-4205-ba31-6ed8a212732e
  sha: 514bc3df30b24eb0a06533f1ebaa579b898990f5
  size: 27973
nginx/nginx-upload-module-2.2.tar.gz:
  object_id: 502854f1-9823-468f-baef-1a8d68823ead
  sha: 74ccd116525a155db76f92a1cd484d9516a70398
  size: 28505
nginx/newrelic_nginx_agent.tar.gz:
  object_id: cad4fada-4a11-4b1a-a884-c6f58dacead9
  sha: 98a1b10475371705932fea4769f8ac1b0451106f
  size: 5222
cli/cf-linux-amd64.tgz:
  object_id: 94c687ca-00f3-4ef1-98f8-401a915100eb
  sha: ea9477a5336baef3b554c2c8767dcb4224b22226
  size: 5644552
golang/go1.4.3.linux-amd64.tar.gz:
  object_id: 17b23a63-49af-467c-8893-db57a059d7b3
  sha: 332b64236d30a8805fc8dd8b3a269915b4c507fe
  size: 61210288
consul/consul-template_0.9.0_linux_amd64.tar.gz:
  object_id: e83bcdcd-2f31-4b73-8cf8-516d54e8f59a
  sha: a44e441f9347abe64956e5bb30c4d4b0464d1f73
  size: 2460384
uaa/newrelic.jar:
  object_id: 2b9d1b59-bc86-4089-95ba-2c0374fe3737
  sha: a5070963fc84bea27acc1d492cb9e3143f0c4715
  size: 7064901
uaa/apache-tomcat-7.0.61.tar.gz:
  object_id: fdad7b89-61f5-4cd1-a003-49c4d872412b
  sha: 98ccbc95d029291e81bf818879ec8a0aa14465df
  size: 8816567
consul/consul_0.5.2_linux_amd64.zip:
  object_id: 74107b66-7502-4e06-bdc2-d2dbea1e73c6
  sha: b3ae610c670fc3b81737d44724ebde969da66ebf
  size: 4803609
binary-buildpack/binary_buildpack-cached-v1.0.1.zip:
  object_id: ada385dd-f0b6-43c7-8429-0057766116cc
  sha: 3e62e3882495cf16686078e7209bf28d3f9d60f5
  size: 8487
haproxy/haproxy-1.5.14.tar.gz:
  object_id: 02657a44-3292-4e0b-8b18-bcad061a2381
  sha: 159f5beb8fdc6b8059ae51b53dc935d91c0fb51f
  size: 1345345
haproxy/pcre-8.37.tar.gz:
  object_id: 22601a5f-4ef4-4621-80aa-0fa1f8067db6
  sha: 4a24a20c61347d8da4edc86d5475aaf70ac146bb
  size: 2041593
nginx/pcre-8.37.tar.gz:
  object_id: 262a1857-da10-4680-b148-52d7803af7ae
  sha: 4a24a20c61347d8da4edc86d5475aaf70ac146bb
  size: 2041593
nginx/nginx-1.8.0.tar.gz:
  object_id: 0d18bbee-b79d-4fec-bba5-635821969fa0
  sha: 12bad312764feae50246685ab2e74512d1aa9b2f
  size: 832104
ruby-2.2.4/bundler-1.10.6.gem:
  object_id: 74aa8a43-e1f6-43d5-b90d-e86a01b2e404
  sha: 55a37fccd1c0cb5542d468e35d3be46dd0667f73
  size: 251392
ruby-2.2.4/ruby-2.2.4.tar.gz:
  object_id: bb355996-b778-4c98-939c-9716c81f03cd
  sha: 818e5e157f76d4912ba3a7c7b4fc5156105e83c3
  size: 16638151
ruby-2.2.4/rubygems-2.4.8.tgz:
  object_id: 998e4fd8-fd28-4b7d-8870-5394c26e8303
  sha: 0db6b2f1cdd2267fe19f1f875057c2f2ce9f5696
  size: 447712
uaa/cloudfoundry-identity-statsd-1.0.0.war:
  object_id: 03f0688e-c6f3-4a27-8d5c-694b4dda0907
  sha: 038c11e503bdbc5194c76535b22f5d4b85aeb37f
  size: 11163261
openjdk/openjdk-1.8.0_65-x86_64-mountainlion.tar.gz:
  object_id: af9d49da-273e-4b1f-acb7-53d828ff6d7f
  sha: 0d0fef95aa7bdd494f8aac2fa4d94f84b2b3ee9d
  size: 81922523
openjdk/openjdk-1.8.0_65-x86_64-trusty-jre.tar.gz:
  object_id: 7d781bd3-d5d8-485d-9bc5-252e55094d33
  sha: e5ecfe29a74bca1794eb18de03f2f98495c5cbc0
  size: 77054579
openjdk/openjdk-1.8.0_65-x86_64-trusty.tar.gz:
  object_id: 3a1c2b78-c32c-433c-984f-1c60ead8b797
  sha: 949812223e334ba6c360a097a44084776eaee418
  size: 77611856
ruby-2.1.8/bundler-1.9.4.gem:
  object_id: 25f8ce04-957f-4e17-acd2-f9825a87d132
  sha: ea3f17a76a8249049b5589c9b5421af72189babc
  size: 244224
ruby-2.1.8/ruby-2.1.8.tar.gz:
  object_id: 6e90c843-f647-4f85-80f2-769cd3688258
  sha: c7e50159357afd87b13dc5eaf4ac486a70011149
  size: 15154017
ruby-2.1.8/yaml-0.1.6.tar.gz:
  object_id: 63b9ac28-38d6-4698-bd99-908f80e90405
  sha: f3d404e11bec3c4efcddfd14c42d46f1aabe0b5d
  size: 503012
python-buildpack/python_buildpack-cached-v1.5.4.zip:
  object_id: d41bc9e8-4daf-4681-bb96-71a91125c025
  sha: d77d7634925ecb6bb5130bf659dfb7a4f44a1054
  size: 266308206
golang/go1.5.3.linux-amd64.tar.gz:
  object_id: 646ac7b1-2de2-4371-8154-76a2ecd19862
  sha: c5377eca4837968d043b681f00a852a262f0f5f6
  size: 80147269
libmariadb/libmariadb.tar.xz:
  object_id: 4c5f767d-aa47-4c60-be6f-50765e08e9eb
  sha: 4985fd30ffd60de12770153346b4485cd5dcb7ad
  size: 1260684
staticfile-buildpack/staticfile_buildpack-cached-v1.3.1.zip:
  object_id: 756834ff-0523-4251-9032-208f6b81479c
  sha: d84ffdf7306e272d1a09877bb00df9cce1583401
  size: 2548892
java-buildpack/java-buildpack-offline-v3.6.zip:
  object_id: b23c8ace-26f2-4270-94ed-a861995826e2
  sha: 886bd2888127429f7f75120d98a187cbf7289c16
  size: 253316417
java-buildpack/java-buildpack-v3.6.zip:
  object_id: 957d975c-43de-4c1e-83a0-6df8f1a2eb1b
  sha: 3ddf6855baec15fb97cd486312615ce82a354dba
  size: 164535
ruby-buildpack/ruby_buildpack-cached-v1.6.13.zip:
  object_id: 75f96d78-2ff3-4b20-be01-18dda7e7f0bc
  sha: 712fe85a99fe8ea5fcf55e6d96b648ebb2acd66b
  size: 271158934
php-buildpack/php_buildpack-cached-v4.3.5.zip:
  object_id: 58735cb4-8386-4c1a-95e6-ef91218987b4
  sha: 4e7dbfdd1804fa0c052fb19dc5e349c3852180ca
  size: 227617482
nodejs-buildpack/nodejs_buildpack-cached-v1.5.6.zip:
  object_id: fbdabd53-54bf-4c0b-80b3-b27258c81933
  sha: 07684e98dfb04635e58d4373d6e858e9f3c55a8d
  size: 49496944
go-buildpack/go_buildpack-cached-v1.7.3.zip:
  object_id: 44b07e57-13cf-4e5a-a7c3-87c27c86f181
  sha: 68e6bec40374a0b133cdd18ec4850eda7da49bf8
  size: 383960326
rootfs/cflinuxfs2-1.39.0.tar.gz:
  object_id: 4ea3f72d-cf1c-44e6-9e64-a04a379d3b60
  sha: 5af6fbd6df75c59c1aeda5af5030929ad916a1f1
  size: 258521322
postgres/postgresql-9.4.6.tar.gz:
  object_id: 02b3e2ae-cba1-400f-a5a3-e66605d9d103
  sha: bd031beebd86bf149c497525dccf57eebe5a6add
  size: 23249307
