---
debian_nfs_server/nfs-kernel-server_1%3a1.2.0-4ubuntu4.1_amd64.deb:
  object_id: rest/objects/4e4e78bca41e122204e4e9863d076304f307136db190
  sha: a44b3f8319984bace61f21bb6d15cee1419e5bf3
  size: 169618
uaa/cloudfoundry-identity-varz-1.0.2.war:
  object_id: rest/objects/4e4e78bca21e121204e4e86ee151bc050928ba58f527
  sha: 8c35ed35fb6dfc4a97a243447763c635812066e8
  size: 5727747
nginx/headers-more-v0.25.tgz:
  object_id: a621718d-df24-4205-ba31-6ed8a212732e
  sha: 514bc3df30b24eb0a06533f1ebaa579b898990f5
  size: 27973
nginx/nginx-upload-module-2.2.tar.gz:
  object_id: 502854f1-9823-468f-baef-1a8d68823ead
  sha: 74ccd116525a155db76f92a1cd484d9516a70398
  size: 28505
consul/consul-template_0.9.0_linux_amd64.tar.gz:
  object_id: e83bcdcd-2f31-4b73-8cf8-516d54e8f59a
  sha: a44e441f9347abe64956e5bb30c4d4b0464d1f73
  size: 2460384
uaa/newrelic.jar:
  object_id: 2b9d1b59-bc86-4089-95ba-2c0374fe3737
  sha: a5070963fc84bea27acc1d492cb9e3143f0c4715
  size: 7064901
uaa/apache-tomcat-7.0.61.tar.gz:
  object_id: fdad7b89-61f5-4cd1-a003-49c4d872412b
  sha: 98ccbc95d029291e81bf818879ec8a0aa14465df
  size: 8816567
consul/consul_0.5.2_linux_amd64.zip:
  object_id: 74107b66-7502-4e06-bdc2-d2dbea1e73c6
  sha: b3ae610c670fc3b81737d44724ebde969da66ebf
  size: 4803609
binary-buildpack/binary_buildpack-cached-v1.0.1.zip:
  object_id: ada385dd-f0b6-43c7-8429-0057766116cc
  sha: 3e62e3882495cf16686078e7209bf28d3f9d60f5
  size: 8487
haproxy/haproxy-1.5.14.tar.gz:
  object_id: 02657a44-3292-4e0b-8b18-bcad061a2381
  sha: 159f5beb8fdc6b8059ae51b53dc935d91c0fb51f
  size: 1345345
haproxy/pcre-8.37.tar.gz:
  object_id: 22601a5f-4ef4-4621-80aa-0fa1f8067db6
  sha: 4a24a20c61347d8da4edc86d5475aaf70ac146bb
  size: 2041593
nginx/pcre-8.37.tar.gz:
  object_id: 262a1857-da10-4680-b148-52d7803af7ae
  sha: 4a24a20c61347d8da4edc86d5475aaf70ac146bb
  size: 2041593
nginx/nginx-1.8.0.tar.gz:
  object_id: 0d18bbee-b79d-4fec-bba5-635821969fa0
  sha: 12bad312764feae50246685ab2e74512d1aa9b2f
  size: 832104
ruby-2.2.4/bundler-1.10.6.gem:
  object_id: 74aa8a43-e1f6-43d5-b90d-e86a01b2e404
  sha: 55a37fccd1c0cb5542d468e35d3be46dd0667f73
  size: 251392
ruby-2.2.4/ruby-2.2.4.tar.gz:
  object_id: bb355996-b778-4c98-939c-9716c81f03cd
  sha: 818e5e157f76d4912ba3a7c7b4fc5156105e83c3
  size: 16638151
ruby-2.2.4/rubygems-2.4.8.tgz:
  object_id: 998e4fd8-fd28-4b7d-8870-5394c26e8303
  sha: 0db6b2f1cdd2267fe19f1f875057c2f2ce9f5696
  size: 447712
uaa/cloudfoundry-identity-statsd-1.0.0.war:
  object_id: 03f0688e-c6f3-4a27-8d5c-694b4dda0907
  sha: 038c11e503bdbc5194c76535b22f5d4b85aeb37f
  size: 11163261
ruby-2.1.8/bundler-1.9.4.gem:
  object_id: 25f8ce04-957f-4e17-acd2-f9825a87d132
  sha: ea3f17a76a8249049b5589c9b5421af72189babc
  size: 244224
ruby-2.1.8/ruby-2.1.8.tar.gz:
  object_id: 6e90c843-f647-4f85-80f2-769cd3688258
  sha: c7e50159357afd87b13dc5eaf4ac486a70011149
  size: 15154017
ruby-2.1.8/yaml-0.1.6.tar.gz:
  object_id: 63b9ac28-38d6-4698-bd99-908f80e90405
  sha: f3d404e11bec3c4efcddfd14c42d46f1aabe0b5d
  size: 503012
postgres/postgresql-9.4.6.tar.gz:
  object_id: 02b3e2ae-cba1-400f-a5a3-e66605d9d103
  sha: bd031beebd86bf149c497525dccf57eebe5a6add
  size: 23249307
python-buildpack/python_buildpack-cached-v1.5.5.zip:
  object_id: 24c546e2-3609-4c42-ba26-67e1d3d188b3
  sha: ca60152b78be3f93067cd4f03d01e2db810ac2a8
  size: 266456922
staticfile-buildpack/staticfile_buildpack-cached-v1.3.6.zip:
  object_id: 6832b42c-bd5e-41f4-855c-dea41578ce79
  sha: de3bedc191535d4743e0b391458736b183f9209b
  size: 2633884
rootfs/cflinuxfs2-1.51.0.tar.gz:
  object_id: 8244ac30-2c34-4c07-9425-79fc2021ba7e
  sha: 07adb4c6ed597e5d969b34c6777a4a9449295c4c
  size: 276630908
php-buildpack/php_buildpack-cached-v4.3.10.zip:
  object_id: 88d0647c-4f6e-454a-a062-c97346389fdf
  sha: 749aaae1e042fa80b3e79977ea60bb95de257452
  size: 275004851
golang/go1.6.1.linux-amd64.tar.gz:
  object_id: a735e999-7658-44e5-ac69-a037337aa52d
  sha: c73492474dcc7a233772d27e948b74468d9f1849
  size: 84824395
golang/go1.5.4.linux-amd64.tar.gz:
  object_id: a3831241-348f-478b-836c-f86962dcfc79
  sha: 4c919c3390e86e557a8019ea644e835bc493be2a
  size: 80180116
go-buildpack/go_buildpack-cached-v1.7.5.zip:
  object_id: 20da47c7-49f4-4ecd-99d8-53dab72f18ca
  sha: a25a466217b64d5e4d47a6796be8ab23e7b7eeaf
  size: 472145464
ruby-buildpack/ruby_buildpack-cached-v1.6.16.zip:
  object_id: 78abf705-5e0a-469f-be56-fa6f1452ba90
  sha: 202f38bad1a7c142025bb8b27976bf2fc80655c5
  size: 259708164
openjdk/openjdk-1.8.0_91-x86_64-trusty.tar.gz:
  object_id: 7f2bff0a-affc-4a65-8665-4d284fde6a45
  sha: 69c612c7f783aad33f4d73ec9b44e1a2ee50f386
  size: 78278698
openjdk/openjdk-1.8.0_91-x86_64-mountainlion.tar.gz:
  object_id: 27d58881-9532-4c79-a12e-bb1dab3314c3
  sha: 9e916262cf92d6ca0b09f9261d30aeca05f214d7
  size: 75516939
cli/cli-linux-amd64-6.17.0.tgz:
  object_id: 5d117da5-f89b-4f1f-918e-a11d018ddf35
  sha: c552c8f4436a63c2034d47f66fd218426c632112
  size: 6153376
nodejs-buildpack/nodejs_buildpack-cached-v1.5.12.zip:
  object_id: 2fd5afc3-c3aa-44b0-bbac-39b131858a59
  sha: 7cde788034ed3b3a43bd0ee2dd6233296cf88c7d
  size: 73321448
java-buildpack/java-buildpack-v3.7.zip:
  object_id: 6ef251e1-04e7-4924-aebb-5b1339f8f4de
  sha: 483c35cf7cc87e2ebb05b2b49ebd1f3223105ec8
  size: 172718
java-buildpack/java-buildpack-offline-v3.7.zip:
  object_id: 8764bda0-fb49-462d-9161-8bb0157e3b7a
  sha: e6cc674d44a9fa0700f993d91f6e49432f6c3109
  size: 291413238
libmariadb/libmariadb-5.5.36.tar.xz:
  object_id: 4d6e5c2c-76be-4df0-9fdd-4eea3b3563a2
  sha: 4985fd30ffd60de12770153346b4485cd5dcb7ad
  size: 1260684
nginx/newrelic_nginx_agent-1.2.1.tar.gz:
  object_id: c1534fd2-f0f4-4f64-be14-49de4e450173
  sha: 98a1b10475371705932fea4769f8ac1b0451106f
  size: 5222
