---
postgres/postgres-9.0.3-1.amd64.tar.gz:
  object_id: rest/objects/4e4e78bca31e122004e4e8ec646e2104f306af917d30
  sha: e47ee9c841ecde4df121f44df282aeb3c50a48d2
  size: 16203511
postgres/postgres-9.0.3-1.i386.tar.gz:
  object_id: rest/objects/4e4e78bca21e121004e4e7d511f55304f306b0371f99
  sha: b2bde31e720eb219bfdc9f1b784f985ecca2cbfb
  size: 15111387
postgres/postgresql-9.0.3.tar.gz:
  object_id: rest/objects/4e4e78bca21e122004e4e8ec647a5404f306b0ec246e
  sha: c8fb5d1d7930e78211e554bb5751183a8148d0ee
  size: 18335858
debian_nfs_server/nfs-kernel-server_1%3a1.2.0-4ubuntu4.1_amd64.deb:
  object_id: rest/objects/4e4e78bca41e122204e4e9863d076304f307136db190
  sha: a44b3f8319984bace61f21bb6d15cee1419e5bf3
  size: 169618
mysql/client-5.1.62-rel13.3-435-Linux-x86_64.tar.gz:
  object_id: rest/objects/4e4e78bca21e122204e4e9863926b104fb68b259c9fc
  sha: 6e5a17195831688a5f14f20aa5d9cd5d5f4164db
  size: 4105211
uaa/cloudfoundry-identity-varz-1.0.2.war:
  object_id: rest/objects/4e4e78bca21e121204e4e86ee151bc050928ba58f527
  sha: 8c35ed35fb6dfc4a97a243447763c635812066e8
  size: 5727747
buildpack_cache/ruby-1.8.7.tgz:
  object_id: ffc863f6-5894-43bb-bd74-684a2931f840
  sha: 3705f4f89550f6f582da9f25af1a715c716a4394
  size: 4402111
buildpack_cache/ruby-1.9.2.tgz:
  object_id: ae2f9381-a54b-47bf-a7d1-eb561eb365ae
  sha: ecdc8bb8975e686d0f1b0ac447b2b5ffc0b4ea1d
  size: 10143524
buildpack_cache/ruby-1.9.3.tgz:
  object_id: 592c86e7-07fe-4106-a55f-b8c190935fa4
  sha: 2a65301f3a28a7edf77c07eccc4d9a57c9513491
  size: 10823804
buildpack_cache/ruby-build-1.8.7.tgz:
  object_id: e9e587a7-d9c1-4791-bb6d-423c6aa2028e
  sha: 5c75a1a553d9b74d529b6929c2d1b89b21eff528
  size: 4400433
buildpack_cache/ruby-build-1.9.2.tgz:
  object_id: f4fc6c65-967a-4b59-bb31-2ee1848bcd1f
  sha: 653b94a70ad61d844934c0b0d6e2d3f9f3b6a892
  size: 10148015
buildpack_cache/bundler-1.3.0.pre.5.tgz:
  object_id: rest/objects/4e4e78bca51e122004e4e8ec68407705135451b3613c
  sha: aba7a30dfe6cc83005d940e1bcc33ef9ad506001
  size: 488313
buildpack_cache/libyaml-0.1.4.tgz:
  object_id: rest/objects/4e4e78bca11e122204e4e98638b76305135451d5b5b4
  sha: e8f66dbdbe6afbf434be4b5d81798f0ccfa48d04
  size: 61085
buildpack_cache/ruby_versions.yml:
  object_id: 48273e57-a228-4e75-9ab4-42bc743dd0ca
  sha: e4335b3ab4cbb8d1c0456f8c361dbe73fd6bb61f
  size: 56
buildpack_cache/bundler-1.3.1.tgz:
  object_id: rest/objects/4e4e78bca51e121004e4e7d51906cd05138e626d7fde
  sha: 6d2ca955af6a26341b3cc27266ec62a20d7d9a11
  size: 231
buildpack_cache/ruby-2.0.0.tgz:
  object_id: 5a0cf225-33f3-4952-8c38-e8b8b1336270
  sha: 207b9640a542fc69a28ce4f5a8e29df11ec90ce5
  size: 11855025
buildpack_cache/apache-tomcat-7.0.37.tar.gz:
  object_id: rest/objects/4e4e78bca11e121204e4e86ee15294051391912aabfc
  sha: c720975d6ebefa071eb94fdb27f13f53e8884811
  size: 7814288
buildpack_cache/mysql-connector-java-5.1.12.jar:
  object_id: rest/objects/4e4e78bca31e122004e4e8ec646e210513919176a21b
  sha: 14ae02cc2adb2aed677080a0c0356e7569e298ec
  size: 732695
buildpack_cache/postgresql-9.0-801.jdbc4.jar:
  object_id: rest/objects/4e4e78bca21e122004e4e8ec647a5405139194eb046e
  sha: 153f2f92a786f12fc111d0111f709012df87c808
  size: 539705
buildpack_cache/rails3_serve_static_assets.tgz:
  object_id: rest/objects/4e4e78bca11e121204e4e86ee15294051392d6fc4542
  sha: 4a6c61905cd342074d3e60773275f308a31ace64
  size: 251
buildpack_cache/rails_log_stdout.tgz:
  object_id: rest/objects/4e4e78bca11e122004e4e8ec648431051392d7483b01
  sha: c7f6b3ca602628d438b6389e61b26e206e2e3727
  size: 719
buildpack_cache/bundler-1.3.2.tgz:
  object_id: rest/objects/4e4e78bca31e121204e4e86ee396920513f7d717207f
  sha: 6c299b755c90f186e7ce677e413e3c2a34d92f70
  size: 810851
buildpack_cache/auto-reconfiguration-0.6.6.jar:
  object_id: rest/objects/4e4e78bca61e122004e4e8ec6b44b605143c13d7a667
  sha: 4102755fcf787345e88668404589481920dcc732
  size: 707752
buildpack_cache/play-jpa-plugin-0.6.6.jar:
  object_id: rest/objects/4e4e78bca51e121004e4e7d51906cd051420648c02a0
  sha: 3df7c473533d1ffe4e5f2d0360f8d412280f9627
  size: 4320
buildpack_cache/openjdk-1.6.0_27.tar.gz:
  object_id: 51513056-c453-44af-a77c-1fdad381d6ad
  sha: a45b6f89ba54d230cb47992bd8177d211f64bd93
  size: 28917046
buildpack_cache/openjdk-1.7.0_21.tar.gz:
  object_id: c40ed53f-2fd2-433c-bf50-cae768348ccd
  sha: 9496529c3fbb9bbe2225d08f999b077c2adcbf12
  size: 31171473
buildpack_cache/openjdk-1.8.0_M7.tar.gz:
  object_id: 4a52e8ee-08c1-4dde-a4f0-cbbc96e8c393
  sha: dffd8aa07504754e25adff9547dce6a366c45d14
  size: 38150032
buildpack_cache/apache-tomcat-7.0.40.tar.gz:
  object_id: 3094e931-972d-4430-abd5-2da9700a0151
  sha: 2fe185842076458da57b54f0a2cc3f5b41ae007d
  size: 7843733
buildpack_cache/apache-tomcat-7.0.41.tar.gz:
  object_id: bd326ac9-6287-4fa2-980c-966d3ad11dc6
  sha: 87974fcc24711ea253fb43e3db450664e02e1adf
  size: 7946142
buildpack_cache/auto-reconfiguration-0.6.7.jar:
  object_id: f793a3c6-fd8d-47af-9e90-4a966b3d2ed2
  sha: 728228f3648d679759df04fce6220d446e5fdd9f
  size: 708374
buildpack_cache/openjdk-1.7.0_25.tar.gz:
  object_id: 3e47e45f-2f65-42f6-ac29-bc9782c3714e
  sha: 37b4cbb2e882f8da9944729e9f311f8f71cc7fdf
  size: 31516851
buildpack_cache/auto-reconfiguration-0.6.8.jar:
  object_id: a7381813-ffd3-44d4-b5b8-8cd47449239d
  sha: 268260039c6f2587c5cc43c2b573ee88b4dbec0c
  size: 709165
nginx/headers-more-v0.25.tgz:
  object_id: a621718d-df24-4205-ba31-6ed8a212732e
  sha: 514bc3df30b24eb0a06533f1ebaa579b898990f5
  size: 27973
nginx/nginx-upload-module-2.2.tar.gz:
  object_id: 502854f1-9823-468f-baef-1a8d68823ead
  sha: 74ccd116525a155db76f92a1cd484d9516a70398
  size: 28505
nginx/newrelic_nginx_agent.tar.gz:
  object_id: cad4fada-4a11-4b1a-a884-c6f58dacead9
  sha: 98a1b10475371705932fea4769f8ac1b0451106f
  size: 5222
golang/go1.2.1.linux-amd64.tar.gz:
  object_id: a5a3eaf9-54ac-47b6-bcf7-5ad59eafe787
  sha: 7605f577ff6ac2d608a3a4e829b255ae2ebc8dcf
  size: 56123695
uaa/openjdk-1.7.0_51.tar.gz:
  object_id: 67b767f3-4032-4970-8535-05dbf7c696a5
  sha: 0f4d3705e3a4e1452250def57cfc36ab6cc37355
  size: 34729532
uaa/openjdk-1.7.0-u40-unofficial-linux-amd64.tgz:
  object_id: 869c365a-7c65-4454-8c09-212d01fa0fb1
  sha: bb41c68e0dc26ad71635d4bff8da16246ded10f0
  size: 42574624
uaa/openjdk-1.7.0-u40-unofficial-macosx-x86_64-bundle.tgz:
  object_id: 4cfb77f4-ea89-4d3d-85ad-2d0f3d84e676
  sha: ac7febc5bbff2dedf8add624a727a4c0ac6c3d10
  size: 65991397
cli/cf-darwin-amd64.tgz:
  object_id: 5de011ed-b541-411f-bc22-dd8723567ee1
  sha: 01590797213107447a54cc68f9fec4de50ed3ddd
  size: 4753530
cli/cf-linux-amd64.tgz:
  object_id: 67983167-946b-423b-8d41-18b678f9051c
  sha: f845800310e4b702a39a2f1191e3d71862630103
  size: 4803309
golang/go1.3.1.linux-amd64.tar.gz:
  object_id: b4778c9a-1994-4dda-b7a2-97ae93e1b835
  sha: 3af011cc19b21c7180f2604fd85fbc4ddde97143
  size: 51930765
uaa/apache-tomcat-7.0.55.tar.gz:
  object_id: 23a06e10-020a-46a1-9af0-62c8c0e02aaf
  sha: 4e23f1e3d6d24e0affebe78f6f5c5d5a49eb4e37
  size: 8941662
ruby-2.1.4/bundler-1.7.4.gem:
  object_id: bef69ead-5089-44e4-bf9c-113737aeb4c9
  sha: e11eb7f9b807f5b7f3beb7c23a06803c7484aebc
  size: 301568
ruby-2.1.4/ruby-2.1.4.tar.gz:
  object_id: 69165e9f-ec26-410a-986a-f6855862846c
  sha: 29e9cfdd9e989b7621d7696ef3f970262a08dbc3
  size: 15127418
ruby-2.1.4/rubygems-2.4.2.tgz:
  object_id: 7d77db2c-b21d-4b05-a4e3-25e71154e11d
  sha: 538f7a264798377e5a63056f979c43f441613ff3
  size: 440555
ruby-2.1.4/yaml-0.1.6.tar.gz:
  object_id: b3ed7d5e-4c46-4c81-8ac7-04d070dd9cc8
  sha: f3d404e11bec3c4efcddfd14c42d46f1aabe0b5d
  size: 503012
nodejs-buildpack/nodejs_buildpack-offline-v1.1.1.zip:
  object_id: 7a59cde0-c278-444c-b860-dc8b9b649f45
  sha: dfc4eeb21e6925d3ce5cd0e500cdbe85869cdc16
  size: 437952578
nginx/nginx-1.6.2.tar.gz:
  object_id: 041b7bdb-b770-4c6c-b797-565b7b1a423d
  sha: 1a5458bc15acf90eea16353a1dd17285cf97ec35
  size: 804164
nginx/pcre-8.36.tar.gz:
  object_id: 29a019ba-407b-4dfa-9558-480d6e4f80e0
  sha: fb537757756818133d8157ec878bc11f5a93ef4d
  size: 2009464
haproxy/haproxy-1.5.10.tar.gz:
  object_id: 2238d5ca-1b5d-44fa-8170-e4f0a5b6eabe
  sha: 2af3b740e84f10cbd0c90a78c30a222a24fb2945
  size: 1339873
haproxy/pcre-8.36.tar.gz:
  object_id: 14452555-3661-413e-b65b-2d062bb4281e
  sha: fb537757756818133d8157ec878bc11f5a93ef4d
  size: 2009464
ruby-buildpack/ruby_buildpack-offline-v1.2.1.zip:
  object_id: 76285ca5-30a1-4952-be12-6282fdc47ac4
  sha: 24e8b2f426d0d3729ab91b28b0e192a2118f8e23
  size: 864863823
go-buildpack/go_buildpack-offline-v1.1.2.zip:
  object_id: d2ca131c-795f-4fe8-9885-80382b2c1e43
  sha: aa3ceb76f017421ddb7733352123f7c81e41b14c
  size: 663441909
python-buildpack/python_buildpack-offline-v1.1.2.zip:
  object_id: 1209751c-3cc3-4f58-94b9-88f4bfc08714
  sha: 1dd976beab15c5ec3efe5ad05f2a03c28cec048e
  size: 329659965
php-buildpack/php_buildpack-offline-v3.0.4.zip:
  object_id: 2b135453-7f79-4de6-b8b7-d3c8fbbe75d8
  sha: 3b1b8f426bb96f4a2a47daff6d87aa4aefb3585f
  size: 479764812
rootfs/cflinuxfs2.tar.gz:
  object_id: 3aadca9b-38c6-4531-94d9-75abc253ff8c
  sha: 46e3eb31e76b7fc11db31cf4e2f0a1039a8d05f9
  size: 251842436
rootfs/lucid64.tar.gz:
  object_id: e8404dda-19f8-47e0-b414-63a7947c1c2b
  sha: 9cdd0bdd61b1637affad80bb1ce8f5624e03c7e4
  size: 203019535
golang/go1.4.2.linux-amd64.tar.gz:
  object_id: bfaf73b1-de68-4c94-9a02-555245b2eb8d
  sha: 5020af94b52b65cc9b6f11d50a67e4bae07b0aff
  size: 62442704
java-buildpack/java-buildpack-offline-v2.7.zip:
  object_id: 94d62653-6eef-4067-8617-592637ad4ca2
  sha: e724ff3a87f7a549206dce8438d14ff9327b9168
  size: 295400134
java-buildpack/java-buildpack-v2.7.zip:
  object_id: f669ef7e-31bf-4ceb-b775-4ea029c73c63
  sha: cb523dc4095c894cf5f558fb794bc92a57ddc372
  size: 149529
