---
debian_nfs_server/nfs-kernel-server_1%3a1.2.0-4ubuntu4.1_amd64.deb:
  object_id: rest/objects/4e4e78bca41e122204e4e9863d076304f307136db190
  sha: a44b3f8319984bace61f21bb6d15cee1419e5bf3
  size: 169618
uaa/cloudfoundry-identity-varz-1.0.2.war:
  object_id: rest/objects/4e4e78bca21e121204e4e86ee151bc050928ba58f527
  sha: 8c35ed35fb6dfc4a97a243447763c635812066e8
  size: 5727747
nginx/nginx-upload-module-2.2.tar.gz:
  object_id: 502854f1-9823-468f-baef-1a8d68823ead
  sha: 74ccd116525a155db76f92a1cd484d9516a70398
  size: 28505
uaa/newrelic.jar:
  object_id: 2b9d1b59-bc86-4089-95ba-2c0374fe3737
  sha: a5070963fc84bea27acc1d492cb9e3143f0c4715
  size: 7064901
haproxy/haproxy-1.5.14.tar.gz:
  object_id: 02657a44-3292-4e0b-8b18-bcad061a2381
  sha: 159f5beb8fdc6b8059ae51b53dc935d91c0fb51f
  size: 1345345
haproxy/pcre-8.37.tar.gz:
  object_id: 22601a5f-4ef4-4621-80aa-0fa1f8067db6
  sha: 4a24a20c61347d8da4edc86d5475aaf70ac146bb
  size: 2041593
uaa/cloudfoundry-identity-statsd-1.0.0.war:
  object_id: 03f0688e-c6f3-4a27-8d5c-694b4dda0907
  sha: 038c11e503bdbc5194c76535b22f5d4b85aeb37f
  size: 11163261
ruby-2.1.8/bundler-1.9.4.gem:
  object_id: 25f8ce04-957f-4e17-acd2-f9825a87d132
  sha: ea3f17a76a8249049b5589c9b5421af72189babc
  size: 244224
ruby-2.1.8/ruby-2.1.8.tar.gz:
  object_id: 6e90c843-f647-4f85-80f2-769cd3688258
  sha: c7e50159357afd87b13dc5eaf4ac486a70011149
  size: 15154017
ruby-2.1.8/yaml-0.1.6.tar.gz:
  object_id: 63b9ac28-38d6-4698-bd99-908f80e90405
  sha: f3d404e11bec3c4efcddfd14c42d46f1aabe0b5d
  size: 503012
postgres/postgresql-9.4.6.tar.gz:
  object_id: 02b3e2ae-cba1-400f-a5a3-e66605d9d103
  sha: bd031beebd86bf149c497525dccf57eebe5a6add
  size: 23249307
golang/go1.5.4.linux-amd64.tar.gz:
  object_id: a3831241-348f-478b-836c-f86962dcfc79
  sha: 4c919c3390e86e557a8019ea644e835bc493be2a
  size: 80180116
libmariadb/libmariadb-5.5.36.tar.xz:
  object_id: 4d6e5c2c-76be-4df0-9fdd-4eea3b3563a2
  sha: 4985fd30ffd60de12770153346b4485cd5dcb7ad
  size: 1260684
nginx/newrelic_nginx_agent-1.2.1.tar.gz:
  object_id: c1534fd2-f0f4-4f64-be14-49de4e450173
  sha: 98a1b10475371705932fea4769f8ac1b0451106f
  size: 5222
ruby-2.2.5/ruby-2.2.5.tar.gz:
  object_id: 9a7262fc-f0af-4bba-be5d-b9d59044071a
  sha: 457707459827bd527347a5cee7b4dc509b486713
  size: 16654395
ruby-2.2.5/bundler-1.11.2.gem:
  object_id: 61e0839e-176e-41a1-a13b-ee53337794a3
  sha: 8eb956dec72da753d3d2a2126c78508b17af434e
  size: 263168
ruby-2.2.5/yaml-0.1.6.tar.gz:
  object_id: 1d7ec354-5aa6-4e19-b6e5-51f6d6327814
  sha: f3d404e11bec3c4efcddfd14c42d46f1aabe0b5d
  size: 503012
ruby-2.3/bundler-1.11.2.gem:
  object_id: 5853a4d1-8574-4a5d-ab0b-d72831a79a48
  sha: 8eb956dec72da753d3d2a2126c78508b17af434e
  size: 263168
ruby-2.3/ruby-2.3.1.tar.gz:
  object_id: 95a32294-6f17-45b7-8911-ef6729195536
  sha: c39b4001f7acb4e334cb60a0f4df72d434bef711
  size: 17797997
ruby-2.3/rubygems-2.6.4.tgz:
  object_id: 5e1e754b-85ec-495c-806e-dccf6daec0aa
  sha: 8ef39e536af2ecd20b0e7a95765fa6a485087ac8
  size: 478582
consul/consul-template_0.14.0_linux_amd64.zip:
  object_id: 498b302c-a737-4036-8cc7-14a64493338d
  sha: f932301f69a477253e4e4bf3c60159ea77cf28a8
  size: 3523492
consul/consul_0.6.4_linux_amd64.zip:
  object_id: 817201d3-fa78-4a86-84d9-65ca49eee82a
  sha: 85de555de27cae126f0f89e762f6136e1c7104b6
  size: 6206903
nginx/nginx-1.11.1.tar.gz:
  object_id: ced13588-cd45-44d4-bf76-0f6d668522ea
  sha: 6b6172b26628b95c4ad0d6cb5b11eb4aa59c2a83
  size: 913417
nginx/headers-more-nginx-module-0.30.tar.gz:
  object_id: e8f3c630-e139-46b4-9363-c178f444edca
  sha: a188a399f3e365a0831585a9d7aa0e6ed1a75f0d
  size: 27793
nginx/pcre-8.39.tar.gz:
  object_id: 70c7bafb-4013-4f07-8287-bfb07faa1085
  sha: b3aec1f643d9701841e2f9d57ac121a7ff448fc8
  size: 2062258
cli/cf-cli_6.19.0_linux_x86-64.tgz:
  object_id: 19729ce8-7c1a-47da-8609-bd2d6b8b9b3a
  sha: 625170654ffa4568dae97b4d3915e87557b29261
  size: 6450885
java-buildpack/java-buildpack-offline-v3.8.1.zip:
  object_id: ac228265-41ef-4ce6-a0bc-fcfb11dd270d
  sha: 31a7d013223e75ea8c6aab5f26d2fdf20abe66cc
  size: 258001510
java-buildpack/java-buildpack-v3.8.1.zip:
  object_id: d50a848f-4418-4528-bd70-5712ffc58722
  sha: cb76e8200619be960216b4a48865f8bbe4bdf0ec
  size: 171390
golang/go1.6.3.linux-amd64.tar.gz:
  object_id: 7ad4929c-a987-4b84-b686-3c9598951f25
  sha: 5e916ba4dd8c2fc43beafca4c08b334c4d0686f3
  size: 84856920
binary-buildpack/binary_buildpack-cached-v1.0.3.zip:
  object_id: 0eb81e10-ee29-4f4b-8a62-8a6ba4d1a3a2
  sha: 139e33b71c396dc4406c3b4982d21c23fc77a023
  size: 9406
php-buildpack/php_buildpack-cached-v4.3.17.zip:
  object_id: cec6e4dc-44cf-4867-bdad-96a4dfbf3c05
  sha: 10b526f548d8342804db57390a45b5928788d72a
  size: 293377479
nodejs-buildpack/nodejs_buildpack-cached-v1.5.18.zip:
  object_id: c7787e51-e8dc-43c0-9426-f83ffe0a3b54
  sha: 0af1233c7178d9f20bedc1e9c55f909d0d78bc9d
  size: 102072513
go-buildpack/go_buildpack-cached-v1.7.11.zip:
  object_id: bd67f9b9-373a-4d80-b645-8dcb47341650
  sha: 946219d734e86545c3efc5c56ff2dcdf86db120e
  size: 336411517
staticfile-buildpack/staticfile_buildpack-cached-v1.3.10.zip:
  object_id: 8817deeb-3799-4ea3-96a1-4c282b1f2bd0
  sha: b476477d537f3b4e29b121b7cd4fde0f57bd730f
  size: 2658753
ruby-buildpack/ruby_buildpack-cached-v1.6.21.zip:
  object_id: 9fd588b9-05f8-4b7b-8644-23043f450ff3
  sha: 796d7f88496171f2cd21cb4fe9c04a60a7c20dc5
  size: 273910775
python-buildpack/python_buildpack-cached-v1.5.9.zip:
  object_id: a7aaa36f-a6cc-4739-b5a3-ea94358edf1a
  sha: e7f5f9332a763bbce3ac791370bffd9bede511ae
  size: 268832470
postgres/postgresql-9.4.9.tar.gz:
  object_id: 528861b6-d7c1-4ecd-82b1-d9d56aea62ea
  sha: c9d641eb69885672e5aacee413cd778d88b8420d
  size: 23300245
rootfs/cflinuxfs2-1.77.0.tar.gz:
  object_id: 8360b593-d76b-4cbc-a2e4-ffb29d32ca26
  sha: a1d144210956045e58af13785859b48de407cf03
  size: 276078636
openjdk/openjdk-1.8.0_101-x86_64-trusty.tar.gz:
  object_id: af292af2-8e47-487a-8dfd-c7fd0c04caec
  sha: d77ee059e289ae52fb87812f1a2932268427dc26
  size: 77696717
openjdk/openjdk-1.8.0_101-x86_64-mountainlion.tar.gz:
  object_id: c3dab272-8db3-4bd2-8836-f06e63640a9e
  sha: d9374652844bfd7bcdce8f8b605fb57fd76c9e36
  size: 75550921
uaa/apache-tomcat-8.0.36.tar.gz:
  object_id: b142bb5b-e401-4946-b872-433c91a6a8d3
  sha: c711970918f4c0ebd120cf35605795c416e342c8
  size: 9277365
