---
cli/cf-cli_6.26.0_linux_x86-64.tgz:
  size: 5174999
  object_id: db58b893-9d3e-477e-96ae-9941d3cebea9
  sha: 6fe2df0ef09820a3a46db5cac9152fb8f1ecca02
cli/cf-cli_6.26.0_winx64.zip:
  size: 5239878
  object_id: aefa451b-b95c-4ed1-8c9c-87cdc4266bc6
  sha: 653f3d3b0f93f414ca787e421403e0e0475793ec
consul-windows/consul_0.7.4_windows_amd64.zip:
  size: 8797270
  object_id: 87935063-a863-4036-7ba9-fc213b389a44
  sha: 2832858f6edc1d346f2473411ff1de7c6c2988be
consul/consul-template_0.18.1_linux_amd64.zip:
  size: 2524699
  object_id: cbd638be-b430-439e-61a9-6067900c3a19
  sha: 7328b86dc95ee0106872e7c70eddae9717ed55ec
consul/consul_0.7.4_linux_amd64.zip:
  size: 8764647
  object_id: 81b825c1-2341-4d5c-5d96-72421df420d8
  sha: 5d2ccf2bfe7ec35263fbb582701f01283bf66648
container-networking/v0-14-0-network-policy-plugin-linux64:
  size: 8472248
  object_id: 8fb4ea2d-7f93-4ea4-bfeb-c7b973c2d6b9
  sha: df087aee2480e2ec67a6b0433fddd351b9f2cc21
debian_nfs_server/nfs-kernel-server_1%3a1.2.0-4ubuntu4.1_amd64.deb:
  size: 169618
  object_id: rest/objects/4e4e78bca41e122204e4e9863d076304f307136db190
  sha: a44b3f8319984bace61f21bb6d15cee1419e5bf3
etcd/etcd-v2.2.0-tls1.2-patch-linux-amd64.tar.gz:
  size: 6517667
  object_id: b7a5fbf5-3f8d-461d-a6dc-4440a375b096
  sha: c1315a7a4ecb52f7d3e5b54775a4d8f735dc33f8
expat/expat-2.2.0.tar.bz2:
  size: 414352
  object_id: 879fb468-db40-4462-5c7f-9ae52bb8b8f0
  sha: 8453bc52324be4c796fd38742ec48470eef358b3
golang/go1.6.3.linux-amd64.tar.gz:
  size: 84856920
  object_id: 7ad4929c-a987-4b84-b686-3c9598951f25
  sha: 5e916ba4dd8c2fc43beafca4c08b334c4d0686f3
golang/go1.7.4.linux-amd64.tar.gz:
  size: 84021919
  object_id: 783849db-2186-488f-459f-28d2f22d7b64
  sha: 2e5baf03d1590e048c84d1d5b4b6f2540efaaea1
golang/go1.7.4.windows-amd64.zip:
  size: 90409580
  object_id: dbebd00d-43b7-434d-6603-c7a8fbcbf779
  sha: a0da2f5d67e5b800eba811a34ca4b2aa22cca678
golang/go1.8.linux-amd64.tar.gz:
  size: 89803580
  object_id: 981ceeb2-b4b7-47e2-a3f4-9ca90fe20806
  sha: a93fe8fc245e3554f956bc823f30ef4eb23c2068
golang/go1.8.windows-amd64.zip:
  size: 95976688
  object_id: 643d1977-7a08-4cd1-95e2-86c38435dade
  sha: e31d11df0ac5d8e16a64c8dcfce706589842410f
haproxy/haproxy-1.5.19.tar.gz:
  size: 1362834
  object_id: c1a80f45-f732-4184-917b-ce2cf796ffad
  sha: 8aa56f4cca4c1bf27c82f60ec2a040f91acb0bc1
haproxy/pcre-8.40.tar.gz:
  size: 2065161
  object_id: 7d3a2a29-6c80-40b6-bf77-74d337b99cea
  sha: 10384eb3d411794cc15f55b9d837d3f69e35391e
java-buildpack/java-buildpack-offline-v3.16.zip:
  size: 277353138
  object_id: 8bce5914-014a-4b5e-bd0e-00ec822fcc47
  sha: 0592fe11b2c49aa4dafabc2d0493540174f42c0f
libmariadb/libmariadb-5.5.36.tar.xz:
  size: 1260684
  object_id: 4d6e5c2c-76be-4df0-9fdd-4eea3b3563a2
  sha: 4985fd30ffd60de12770153346b4485cd5dcb7ad
nginx/headers-more-nginx-module-0.32.tar.gz:
  size: 28033
  object_id: b1b5570e-3d28-4b61-b429-734679b2dfed
  sha: aadb7f0b6c5b5b9cae2af72984e03dc2fbf3fecb
nginx/newrelic_nginx_agent-1.2.1.tar.gz:
  size: 5222
  object_id: c1534fd2-f0f4-4f64-be14-49de4e450173
  sha: 98a1b10475371705932fea4769f8ac1b0451106f
nginx/nginx-1.13.4.tar.gz:
  size: 988415
  object_id: 0a846357-7cb9-4920-741d-3193e25531cd
  sha: ee4496ef27fac66cf90aa60c4132215e552a340d
nginx/nginx-dav-ext-module-0.0.3.tar.gz:
  size: 6260
  object_id: 7c7652e1-6c0d-47ad-6015-a0a40a25e859
  sha: 80714f9471cb5c8259ecdca9e25eb32f4d581074
nginx/nginx-upload-module-2.2.tar.gz:
  size: 28505
  object_id: 502854f1-9823-468f-baef-1a8d68823ead
  sha: 74ccd116525a155db76f92a1cd484d9516a70398
nginx/pcre-8.40.tar.gz:
  size: 2065161
  object_id: f544dc8e-0d52-4e54-a80d-0d9419bcfc32
  sha: 10384eb3d411794cc15f55b9d837d3f69e35391e
openjdk/openjdk-1.8.0_141-x86_64-mountainlion.tar.gz:
  size: 75693489
  object_id: af715da0-f5c1-4d5a-5989-90894ab80245
  sha: 5e3d9e5a9b5fcc4a1503dae72246306f712b2fc3
openjdk/openjdk-1.8.0_141-x86_64-trusty.tar.gz:
  size: 78460327
  object_id: 1a6017ca-e6bc-4704-418d-7ca2569bc16e
  sha: bec09ecc5092b6211f1a40367ff021d6de65279c
postgres/postgresql-9.4.9.tar.gz:
  size: 23300245
  object_id: 528861b6-d7c1-4ecd-82b1-d9d56aea62ea
  sha: c9d641eb69885672e5aacee413cd778d88b8420d
postgres/postgresql-9.6.2.tar.gz:
  size: 25450827
  object_id: 0accb732-2327-4b3e-bf1c-af4bbe466ef8
  sha: 3159151f2fc74ec3e684ec0dc8949494b608fb3c
postgres/postgresql-9.6.3.tar.gz:
  size: 25536998
  object_id: fdf49a31-a873-41fa-9739-5747a0e5e439
  sha: f596ca487e0c4d41ccc628b1d69b180fb23402db
ruby-2.1.8/bundler-1.9.4.gem:
  size: 244224
  object_id: 25f8ce04-957f-4e17-acd2-f9825a87d132
  sha: ea3f17a76a8249049b5589c9b5421af72189babc
ruby-2.1.8/ruby-2.1.8.tar.gz:
  size: 15154017
  object_id: 6e90c843-f647-4f85-80f2-769cd3688258
  sha: c7e50159357afd87b13dc5eaf4ac486a70011149
ruby-2.1.8/yaml-0.1.6.tar.gz:
  size: 503012
  object_id: 63b9ac28-38d6-4698-bd99-908f80e90405
  sha: f3d404e11bec3c4efcddfd14c42d46f1aabe0b5d
ruby-2.2.5/bundler-1.11.2.gem:
  size: 263168
  object_id: 61e0839e-176e-41a1-a13b-ee53337794a3
  sha: 8eb956dec72da753d3d2a2126c78508b17af434e
ruby-2.2.5/ruby-2.2.5.tar.gz:
  size: 16654395
  object_id: 9a7262fc-f0af-4bba-be5d-b9d59044071a
  sha: 457707459827bd527347a5cee7b4dc509b486713
ruby-2.2.5/yaml-0.1.6.tar.gz:
  size: 503012
  object_id: 1d7ec354-5aa6-4e19-b6e5-51f6d6327814
  sha: f3d404e11bec3c4efcddfd14c42d46f1aabe0b5d
ruby-2.3/bundler-1.14.6.gem:
  size: 319488
  object_id: 9272407d-b107-469a-4055-1db6178d33e3
  sha: 3e84d3a4dd43bfaec988b029f45c0d7ffa205ab8
ruby-2.3/ruby-2.3.3.tar.gz:
  size: 17813577
  object_id: 218c9c26-c0b4-4115-84d1-9f0283d6d633
  sha: 1014ee699071aa2ddd501907d18cbe15399c997d
ruby-2.3/rubygems-2.6.8.tgz:
  size: 754300
  object_id: 2393318f-83ea-4e9c-9d18-83d82ee34d94
  sha: d253fd1caca6103a9e2a69127ac158a3745fbb44
uaa/newrelic.jar:
  size: 7064901
  object_id: 2b9d1b59-bc86-4089-95ba-2c0374fe3737
  sha: a5070963fc84bea27acc1d492cb9e3143f0c4715
ruby-2.2.5/bundler-1.15.0.gem:
  object_id: f839ea17-d873-4e56-bdbf-3827d1e22ad9
  sha: 10feaa6564d972673b21652fbecab24fb5bbdc95
  size: 338432
golang/go1.8.3.windows-amd64.zip:
  object_id: 1aeb9d98-da6a-4042-8dd0-ec1a135cfe7f
  sha: 8a539ecd86505aca6e70e7e561a2b5877d91c000
  size: 96254597
golang/go1.8.3.linux-amd64.tar.gz:
  object_id: 7c7afa17-ac33-43f5-9a1b-5ecc01cde3a1
  sha: 838c415896ef5ecd395dfabde5e7e6f8ac943c8e
  size: 90029041
java-buildpack/java-buildpack-v3.19.zip:
  object_id: bf73c6c7-1533-4aff-a7d0-6a026a2984b7
  sha: c0a633f9564982655ae008f7baa3e51a40b3d6f3
  size: 190751
uaa/apache-tomcat-8.5.16.tar.gz:
  size: 9417469
  object_id: eeb161ee-4b05-4480-7378-8ef36d532545
  sha: 6ae7b007fc17eb2821585e2651edaca90708a75b
go-buildpack/go-buildpack-v1.8.6.zip:
  object_id: 2025f30e-f4d6-4150-b838-10988f7aa5b0
  sha: 93ab4ceecf49967c003f0ea0f023dd9261aaa770
  size: 4795726
binary-buildpack/binary-buildpack-v1.0.14.zip:
  object_id: 0cc798e8-4629-4ba2-b737-7c02b05c9381
  sha: 04822369d716467bf471eb5d4c6adf8627e71184
  size: 63404
php-buildpack/php-buildpack-v4.3.40.zip:
  object_id: d4cce623-ea69-4a9e-a1c3-ab9058fb4472
  sha: 98663827faba2c584e6315cdb4eca21a24344170
  size: 289494
ruby-buildpack/ruby-buildpack-v1.6.47.zip:
  object_id: c81f4df6-1678-49eb-a460-9de8d54d4c8b
  sha: b5913e53fd679ed2ebe0cf1889d3118fd9c11970
  size: 83587
nodejs-buildpack/nodejs-buildpack-v1.6.6.zip:
  object_id: 8eb068db-77ca-4165-9d6c-52969b2fddf9
  sha: 1b85496d53d2e90fc6e853f86a119275558737b3
  size: 3627496
python-buildpack/python-buildpack-v1.5.24.zip:
  object_id: a1a81524-5087-4fe8-ba03-90a439f28c91
  sha: de8e4b137ba7056ea86912f8f21be13b4cc075c1
  size: 81357
dotnet-core-buildpack/dotnet-core-buildpack-v1.0.24.zip:
  object_id: 9daf3b8e-7d04-4088-a961-b4a9f0db2bf4
  sha: 8d75ce7b47ff80a7e9f77cc3b1c7ceffee323bc7
  size: 91504
staticfile-buildpack/staticfile-buildpack-v1.4.14.zip:
  object_id: 885877be-ed16-4f7f-b8f5-31d5bc88a90a
  sha: 8f1fd07f2207fe48f1f51c082d29329bb53091f0
  size: 4073282
