---
debian_nfs_server/nfs-kernel-server_1%3a1.2.0-4ubuntu4.1_amd64.deb:
  object_id: rest/objects/4e4e78bca41e122204e4e9863d076304f307136db190
  sha: a44b3f8319984bace61f21bb6d15cee1419e5bf3
  size: 169618
uaa/cloudfoundry-identity-varz-1.0.2.war:
  object_id: rest/objects/4e4e78bca21e121204e4e86ee151bc050928ba58f527
  sha: 8c35ed35fb6dfc4a97a243447763c635812066e8
  size: 5727747
nginx/headers-more-v0.25.tgz:
  object_id: a621718d-df24-4205-ba31-6ed8a212732e
  sha: 514bc3df30b24eb0a06533f1ebaa579b898990f5
  size: 27973
nginx/nginx-upload-module-2.2.tar.gz:
  object_id: 502854f1-9823-468f-baef-1a8d68823ead
  sha: 74ccd116525a155db76f92a1cd484d9516a70398
  size: 28505
consul/consul-template_0.9.0_linux_amd64.tar.gz:
  object_id: e83bcdcd-2f31-4b73-8cf8-516d54e8f59a
  sha: a44e441f9347abe64956e5bb30c4d4b0464d1f73
  size: 2460384
uaa/newrelic.jar:
  object_id: 2b9d1b59-bc86-4089-95ba-2c0374fe3737
  sha: a5070963fc84bea27acc1d492cb9e3143f0c4715
  size: 7064901
uaa/apache-tomcat-7.0.61.tar.gz:
  object_id: fdad7b89-61f5-4cd1-a003-49c4d872412b
  sha: 98ccbc95d029291e81bf818879ec8a0aa14465df
  size: 8816567
consul/consul_0.5.2_linux_amd64.zip:
  object_id: 74107b66-7502-4e06-bdc2-d2dbea1e73c6
  sha: b3ae610c670fc3b81737d44724ebde969da66ebf
  size: 4803609
haproxy/haproxy-1.5.14.tar.gz:
  object_id: 02657a44-3292-4e0b-8b18-bcad061a2381
  sha: 159f5beb8fdc6b8059ae51b53dc935d91c0fb51f
  size: 1345345
haproxy/pcre-8.37.tar.gz:
  object_id: 22601a5f-4ef4-4621-80aa-0fa1f8067db6
  sha: 4a24a20c61347d8da4edc86d5475aaf70ac146bb
  size: 2041593
nginx/pcre-8.37.tar.gz:
  object_id: 262a1857-da10-4680-b148-52d7803af7ae
  sha: 4a24a20c61347d8da4edc86d5475aaf70ac146bb
  size: 2041593
nginx/nginx-1.8.0.tar.gz:
  object_id: 0d18bbee-b79d-4fec-bba5-635821969fa0
  sha: 12bad312764feae50246685ab2e74512d1aa9b2f
  size: 832104
uaa/cloudfoundry-identity-statsd-1.0.0.war:
  object_id: 03f0688e-c6f3-4a27-8d5c-694b4dda0907
  sha: 038c11e503bdbc5194c76535b22f5d4b85aeb37f
  size: 11163261
ruby-2.1.8/bundler-1.9.4.gem:
  object_id: 25f8ce04-957f-4e17-acd2-f9825a87d132
  sha: ea3f17a76a8249049b5589c9b5421af72189babc
  size: 244224
ruby-2.1.8/ruby-2.1.8.tar.gz:
  object_id: 6e90c843-f647-4f85-80f2-769cd3688258
  sha: c7e50159357afd87b13dc5eaf4ac486a70011149
  size: 15154017
ruby-2.1.8/yaml-0.1.6.tar.gz:
  object_id: 63b9ac28-38d6-4698-bd99-908f80e90405
  sha: f3d404e11bec3c4efcddfd14c42d46f1aabe0b5d
  size: 503012
postgres/postgresql-9.4.6.tar.gz:
  object_id: 02b3e2ae-cba1-400f-a5a3-e66605d9d103
  sha: bd031beebd86bf149c497525dccf57eebe5a6add
  size: 23249307
golang/go1.6.1.linux-amd64.tar.gz:
  object_id: a735e999-7658-44e5-ac69-a037337aa52d
  sha: c73492474dcc7a233772d27e948b74468d9f1849
  size: 84824395
golang/go1.5.4.linux-amd64.tar.gz:
  object_id: a3831241-348f-478b-836c-f86962dcfc79
  sha: 4c919c3390e86e557a8019ea644e835bc493be2a
  size: 80180116
openjdk/openjdk-1.8.0_91-x86_64-trusty.tar.gz:
  object_id: 7f2bff0a-affc-4a65-8665-4d284fde6a45
  sha: 69c612c7f783aad33f4d73ec9b44e1a2ee50f386
  size: 78278698
openjdk/openjdk-1.8.0_91-x86_64-mountainlion.tar.gz:
  object_id: 27d58881-9532-4c79-a12e-bb1dab3314c3
  sha: 9e916262cf92d6ca0b09f9261d30aeca05f214d7
  size: 75516939
cli/cli-linux-amd64-6.17.0.tgz:
  object_id: 5d117da5-f89b-4f1f-918e-a11d018ddf35
  sha: c552c8f4436a63c2034d47f66fd218426c632112
  size: 6153376
libmariadb/libmariadb-5.5.36.tar.xz:
  object_id: 4d6e5c2c-76be-4df0-9fdd-4eea3b3563a2
  sha: 4985fd30ffd60de12770153346b4485cd5dcb7ad
  size: 1260684
nginx/newrelic_nginx_agent-1.2.1.tar.gz:
  object_id: c1534fd2-f0f4-4f64-be14-49de4e450173
  sha: 98a1b10475371705932fea4769f8ac1b0451106f
  size: 5222
ruby-2.2.5/ruby-2.2.5.tar.gz:
  object_id: 9a7262fc-f0af-4bba-be5d-b9d59044071a
  sha: 457707459827bd527347a5cee7b4dc509b486713
  size: 16654395
ruby-2.2.5/bundler-1.11.2.gem:
  object_id: 61e0839e-176e-41a1-a13b-ee53337794a3
  sha: 8eb956dec72da753d3d2a2126c78508b17af434e
  size: 263168
ruby-2.2.5/yaml-0.1.6.tar.gz:
  object_id: 1d7ec354-5aa6-4e19-b6e5-51f6d6327814
  sha: f3d404e11bec3c4efcddfd14c42d46f1aabe0b5d
  size: 503012
ruby-2.3/bundler-1.11.2.gem:
  object_id: 5853a4d1-8574-4a5d-ab0b-d72831a79a48
  sha: 8eb956dec72da753d3d2a2126c78508b17af434e
  size: 263168
ruby-2.3/ruby-2.3.1.tar.gz:
  object_id: 95a32294-6f17-45b7-8911-ef6729195536
  sha: c39b4001f7acb4e334cb60a0f4df72d434bef711
  size: 17797997
ruby-2.3/rubygems-2.6.4.tgz:
  object_id: 5e1e754b-85ec-495c-806e-dccf6daec0aa
  sha: 8ef39e536af2ecd20b0e7a95765fa6a485087ac8
  size: 478582
binary-buildpack/binary_buildpack-cached-v1.0.2.zip:
  object_id: a2708afe-cd7b-4934-8ced-4f068315994c
  sha: a32d9ae40371d557c7c90eb2affc3d7bba6abe69
  size: 9358
php-buildpack/php_buildpack-cached-v4.3.12.zip:
  object_id: 36152337-93d9-4d99-9120-f3b7a04d3e42
  sha: de0d8945a76c3b1206e16509e8a03e50437a5a68
  size: 276744172
nodejs-buildpack/nodejs_buildpack-cached-v1.5.14.zip:
  object_id: 715a3cf6-ec8e-4796-b4eb-9d0dd13c0f27
  sha: ddfaa3b5c17aba2d9303306fb1fbae9aa2574b74
  size: 96046461
staticfile-buildpack/staticfile_buildpack-cached-v1.3.8.zip:
  object_id: fb15e924-4ae7-4b3d-9939-eaf991551d1d
  sha: 8b683c2237056089dea24a2a4d70606e8a4a67cf
  size: 2632036
go-buildpack/go_buildpack-cached-v1.7.8.zip:
  object_id: 0e858596-8fdf-4081-8d16-1febbe060f44
  sha: 5dc19602391fb2571b217d754dd7652e6c76630f
  size: 349407727
ruby-buildpack/ruby_buildpack-cached-v1.6.18.zip:
  object_id: f1232ea4-c5be-4890-9fd9-46b01bf3af0e
  sha: 40aa1780dc549e5556ff418fc8b2cdc5fecfaaf7
  size: 285501145
java-buildpack/java-buildpack-v3.7.1.zip:
  object_id: c75e1df8-4a35-43a9-a30b-552e0c3a8327
  sha: ec1ae2f978e0bb456bcf3145d33ba6c30699f28f
  size: 172718
java-buildpack/java-buildpack-offline-v3.7.1.zip:
  object_id: e63f0cfc-2f29-41c3-8260-44bfb8a61884
  sha: 7e7c46bbbeca84f5d93866e0d39333c53471ee2b
  size: 246540469
python-buildpack/python_buildpack-cached-v1.5.6.zip:
  object_id: cd1d3598-ff44-4752-9826-0fb80223ff95
  sha: 0d1bd59e52f61d4938fba4c01ac221aaa2789c75
  size: 267585855
rootfs/cflinuxfs2-1.63.0.tar.gz:
  object_id: 62c6c1e2-efdc-4e39-8cf7-06709ae55ccd
  sha: ed7b64f3ea806e747b350831d979c4be52ebd842
  size: 275848136
