---
postgres/postgres-9.0.3-1.amd64.tar.gz:
  object_id: rest/objects/4e4e78bca31e122004e4e8ec646e2104f306af917d30
  sha: e47ee9c841ecde4df121f44df282aeb3c50a48d2
  size: 16203511
postgres/postgres-9.0.3-1.i386.tar.gz:
  object_id: rest/objects/4e4e78bca21e121004e4e7d511f55304f306b0371f99
  sha: b2bde31e720eb219bfdc9f1b784f985ecca2cbfb
  size: 15111387
postgres/postgresql-9.0.3.tar.gz:
  object_id: rest/objects/4e4e78bca21e122004e4e8ec647a5404f306b0ec246e
  sha: c8fb5d1d7930e78211e554bb5751183a8148d0ee
  size: 18335858
debian_nfs_server/nfs-kernel-server_1%3a1.2.0-4ubuntu4.1_amd64.deb:
  object_id: rest/objects/4e4e78bca41e122204e4e9863d076304f307136db190
  sha: a44b3f8319984bace61f21bb6d15cee1419e5bf3
  size: 169618
uaa/cloudfoundry-identity-varz-1.0.2.war:
  object_id: rest/objects/4e4e78bca21e121204e4e86ee151bc050928ba58f527
  sha: 8c35ed35fb6dfc4a97a243447763c635812066e8
  size: 5727747
nginx/headers-more-v0.25.tgz:
  object_id: a621718d-df24-4205-ba31-6ed8a212732e
  sha: 514bc3df30b24eb0a06533f1ebaa579b898990f5
  size: 27973
nginx/nginx-upload-module-2.2.tar.gz:
  object_id: 502854f1-9823-468f-baef-1a8d68823ead
  sha: 74ccd116525a155db76f92a1cd484d9516a70398
  size: 28505
nginx/newrelic_nginx_agent.tar.gz:
  object_id: cad4fada-4a11-4b1a-a884-c6f58dacead9
  sha: 98a1b10475371705932fea4769f8ac1b0451106f
  size: 5222
cli/cf-linux-amd64.tgz:
  object_id: d491f12d-a877-4d6f-b304-9c93adcd9ff1
  sha: 1c3cdd94c23c2d72a40d8964167e07216679de0f
  size: 5080879
golang/go1.4.3.linux-amd64.tar.gz:
  object_id: 17b23a63-49af-467c-8893-db57a059d7b3
  sha: 332b64236d30a8805fc8dd8b3a269915b4c507fe
  size: 61210288
consul/consul-template_0.9.0_linux_amd64.tar.gz:
  object_id: e83bcdcd-2f31-4b73-8cf8-516d54e8f59a
  sha: a44e441f9347abe64956e5bb30c4d4b0464d1f73
  size: 2460384
uaa/newrelic.jar:
  object_id: 2b9d1b59-bc86-4089-95ba-2c0374fe3737
  sha: a5070963fc84bea27acc1d492cb9e3143f0c4715
  size: 7064901
uaa/apache-tomcat-7.0.61.tar.gz:
  object_id: fdad7b89-61f5-4cd1-a003-49c4d872412b
  sha: 98ccbc95d029291e81bf818879ec8a0aa14465df
  size: 8816567
postgres/postgresql-9.4.2.tar.gz:
  object_id: 4d807bf7-94bc-449f-a0c3-549642df3085
  sha: 7a70474f9b44fea1b345e48bd5e4418bccf41f3f
  size: 23092865
rtr/rtr-linux-amd64.tgz:
  object_id: 506e3344-e5e8-4576-8e6e-ccd9c33b7f58
  sha: d98c42cbd73c59852d6252b0fd15440d7471a821
  size: 2199020
consul/consul_0.5.2_linux_amd64.zip:
  object_id: 74107b66-7502-4e06-bdc2-d2dbea1e73c6
  sha: b3ae610c670fc3b81737d44724ebde969da66ebf
  size: 4803609
binary-buildpack/binary_buildpack-cached-v1.0.1.zip:
  object_id: ada385dd-f0b6-43c7-8429-0057766116cc
  sha: 3e62e3882495cf16686078e7209bf28d3f9d60f5
  size: 8487
haproxy/haproxy-1.5.14.tar.gz:
  object_id: 02657a44-3292-4e0b-8b18-bcad061a2381
  sha: 159f5beb8fdc6b8059ae51b53dc935d91c0fb51f
  size: 1345345
haproxy/pcre-8.37.tar.gz:
  object_id: 22601a5f-4ef4-4621-80aa-0fa1f8067db6
  sha: 4a24a20c61347d8da4edc86d5475aaf70ac146bb
  size: 2041593
nginx/pcre-8.37.tar.gz:
  object_id: 262a1857-da10-4680-b148-52d7803af7ae
  sha: 4a24a20c61347d8da4edc86d5475aaf70ac146bb
  size: 2041593
nodejs-buildpack/nodejs_buildpack-cached-v1.5.0.zip:
  object_id: 56f5eac1-2449-4e95-a570-8311d40164f7
  sha: 366596bd85b21ca3602b68a0401fca8cfa6217cd
  size: 40771189
ruby-2.1.7/bundler-1.9.4.gem:
  object_id: e158e651-c3ff-4dd0-8f42-f7c2f0e08688
  sha: ea3f17a76a8249049b5589c9b5421af72189babc
  size: 244224
ruby-2.1.7/ruby-2.1.7.tar.gz:
  object_id: 5af4b5ce-4e20-4e26-bda2-c942cb078e38
  sha: e2e195a4a58133e3ad33b955c829bb536fa3c075
  size: 15151458
ruby-2.1.7/yaml-0.1.6.tar.gz:
  object_id: 222e4627-f3f5-4c83-aae6-3c6460aae248
  sha: f3d404e11bec3c4efcddfd14c42d46f1aabe0b5d
  size: 503012
nginx/nginx-1.8.0.tar.gz:
  object_id: 0d18bbee-b79d-4fec-bba5-635821969fa0
  sha: 12bad312764feae50246685ab2e74512d1aa9b2f
  size: 832104
ruby-buildpack/ruby_buildpack-cached-v1.6.7.zip:
  object_id: 9c39f092-cf19-4276-a013-285349ca7d74
  sha: 9d8bdc2e0aa81089322e4d9e4cf37a96fb667a7b
  size: 295134096
openjdk/openjdk-1.8.0_60-x86_64-trusty-jre.tar.gz:
  object_id: 71fc34bf-5878-4cbd-98a9-b5113dccc923
  sha: 00a58600bd56007832f1caca487187c023f10ec5
  size: 45029837
openjdk/openjdk-1.8.0_60-x86_64-mountainlion.tar.gz:
  object_id: 6aec69bd-202a-4c07-bef9-2b66e027a957
  sha: d5adc079c1b1e74957f60e627d225173dbc96286
  size: 81913035
openjdk/openjdk-1.8.0_60-x86_64-trusty.tar.gz:
  object_id: de6ab27d-2469-403d-a47a-d1b82c91a33a
  sha: 1831bb9db77e304c9b0167d5b61350aa83393a22
  size: 77540278
python-buildpack/python_buildpack-cached-v1.5.1.zip:
  object_id: b2ea126f-819b-4049-9a74-efb21f8dfe9f
  sha: 53d27bfb52e823b262188b90386a71db5d68fb27
  size: 224934610
mysqlclient-5.5/libmysqlclient-dev_5.5.44.tar.gz:
  object_id: 31e64230-f356-4522-86d6-413a531996b9
  sha: f6cc741b64084752478009505113a39192d89da9
  size: 1376537
ruby-2.2.3/bundler-1.10.6.gem:
  object_id: 5070dbdd-41b0-4653-a4ff-4fa617daeb97
  sha: 55a37fccd1c0cb5542d468e35d3be46dd0667f73
  size: 251392
ruby-2.2.3/ruby-2.2.3.tar.gz:
  object_id: d56c6fa3-b168-4422-8194-22b75d063302
  sha: 0d9e158534cb31e72740138b8f697b57b448e5c3
  size: 16626772
ruby-2.2.3/rubygems-2.4.8.tgz:
  object_id: 5c360f37-0e25-4092-aacd-bb6411fb0f81
  sha: 0db6b2f1cdd2267fe19f1f875057c2f2ce9f5696
  size: 447712
uaa/cloudfoundry-identity-statsd-1.0.0.war:
  object_id: 03f0688e-c6f3-4a27-8d5c-694b4dda0907
  sha: 038c11e503bdbc5194c76535b22f5d4b85aeb37f
  size: 11163261
go-buildpack/go_buildpack-cached-v1.6.3.zip:
  object_id: 4cab011b-e659-470f-9859-bbe7512f3d3c
  sha: 347faa241102e96518bc2705f57a2e0169c3931a
  size: 580121088
php-buildpack/php_buildpack-cached-v4.2.0.zip:
  object_id: b42a13ef-7abd-47e4-ac2a-6913567724b3
  sha: 2d41060c8d7a0ac5c2c9fc3a458bea1c3c208a13
  size: 340174975
staticfile-buildpack/staticfile_buildpack-cached-v1.2.2.zip:
  object_id: 75f21555-7a6f-4e53-901c-fe925fb50191
  sha: bb51fb6fc9d65faee893f02d18a8373b18619915
  size: 2492036
java-buildpack/java-buildpack-offline-v3.3.1.zip:
  object_id: c891c2fc-b64a-46e8-9020-156e6ec196a2
  sha: 4d0e9d0124c26b5295abb3385bdbcf34f2af767c
  size: 248543697
java-buildpack/java-buildpack-v3.3.1.zip:
  object_id: 9b93af3d-5a81-4510-bac6-f8d2135ccf35
  sha: 34e071ea58c17e2dec93f14052fd351869e45f7c
  size: 155819
rootfs/cflinuxfs2-1.15.0.tar.gz:
  object_id: 3da33833-1fe8-496c-ab16-f5f26d8ebcd3
  sha: 3ec727c1a0a9d3645ef3ccd82adfe4b040895896
  size: 248228998
openjdk/openjdk-1.8.0_51-x86_64-mountainlion.tar.gz:
  object_id: 652e8dba-8213-461a-bf6f-baa6c22c25ad
  sha: 1d6fa87aca3599c15b07a7f96e77db4e0d45fa20
  size: 81845477
openjdk/openjdk-1.8.0_51-x86_64-trusty.tar.gz:
  object_id: dc42f738-7245-4347-ab66-c14cd255adb5
  sha: f467dc147e1774f9b4bf78aeca65d096d135e7b6
  size: 77486128
openjdk/openjdk-1.8.0_51.tar.gz:
  object_id: d106a236-08d5-4ec6-9def-ad18bc645a1b
  sha: 2651c262b7cede077da23e00d3fe6ffd9849a1d6
  size: 44707537