---
postgres/postgres-9.0.3-1.amd64.tar.gz:
  object_id: rest/objects/4e4e78bca31e122004e4e8ec646e2104f306af917d30
  sha: e47ee9c841ecde4df121f44df282aeb3c50a48d2
  size: 16203511
postgres/postgres-9.0.3-1.i386.tar.gz:
  object_id: rest/objects/4e4e78bca21e121004e4e7d511f55304f306b0371f99
  sha: b2bde31e720eb219bfdc9f1b784f985ecca2cbfb
  size: 15111387
postgres/postgresql-9.0.3.tar.gz:
  object_id: rest/objects/4e4e78bca21e122004e4e8ec647a5404f306b0ec246e
  sha: c8fb5d1d7930e78211e554bb5751183a8148d0ee
  size: 18335858
debian_nfs_server/nfs-kernel-server_1%3a1.2.0-4ubuntu4.1_amd64.deb:
  object_id: rest/objects/4e4e78bca41e122204e4e9863d076304f307136db190
  sha: a44b3f8319984bace61f21bb6d15cee1419e5bf3
  size: 169618
mysql/client-5.1.62-rel13.3-435-Linux-x86_64.tar.gz:
  object_id: rest/objects/4e4e78bca21e122204e4e9863926b104fb68b259c9fc
  sha: 6e5a17195831688a5f14f20aa5d9cd5d5f4164db
  size: 4105211
uaa/cloudfoundry-identity-varz-1.0.2.war:
  object_id: rest/objects/4e4e78bca21e121204e4e86ee151bc050928ba58f527
  sha: 8c35ed35fb6dfc4a97a243447763c635812066e8
  size: 5727747
nginx/headers-more-v0.25.tgz:
  object_id: a621718d-df24-4205-ba31-6ed8a212732e
  sha: 514bc3df30b24eb0a06533f1ebaa579b898990f5
  size: 27973
nginx/nginx-upload-module-2.2.tar.gz:
  object_id: 502854f1-9823-468f-baef-1a8d68823ead
  sha: 74ccd116525a155db76f92a1cd484d9516a70398
  size: 28505
nginx/newrelic_nginx_agent.tar.gz:
  object_id: cad4fada-4a11-4b1a-a884-c6f58dacead9
  sha: 98a1b10475371705932fea4769f8ac1b0451106f
  size: 5222
uaa/openjdk-1.7.0_51.tar.gz:
  object_id: 67b767f3-4032-4970-8535-05dbf7c696a5
  sha: 0f4d3705e3a4e1452250def57cfc36ab6cc37355
  size: 34729532
uaa/openjdk-1.7.0-u40-unofficial-linux-amd64.tgz:
  object_id: 869c365a-7c65-4454-8c09-212d01fa0fb1
  sha: bb41c68e0dc26ad71635d4bff8da16246ded10f0
  size: 42574624
uaa/openjdk-1.7.0-u40-unofficial-macosx-x86_64-bundle.tgz:
  object_id: 4cfb77f4-ea89-4d3d-85ad-2d0f3d84e676
  sha: ac7febc5bbff2dedf8add624a727a4c0ac6c3d10
  size: 65991397
cli/cf-linux-amd64.tgz:
  object_id: c1f7d817-ada4-4636-85db-646c497132bd
  sha: a5296502c3258d6e1701adfcce5f33b091f6d018
  size: 4939902
golang/go1.3.1.linux-amd64.tar.gz:
  object_id: b4778c9a-1994-4dda-b7a2-97ae93e1b835
  sha: 3af011cc19b21c7180f2604fd85fbc4ddde97143
  size: 51930765
uaa/apache-tomcat-7.0.55.tar.gz:
  object_id: 23a06e10-020a-46a1-9af0-62c8c0e02aaf
  sha: 4e23f1e3d6d24e0affebe78f6f5c5d5a49eb4e37
  size: 8941662
nginx/nginx-1.6.2.tar.gz:
  object_id: 041b7bdb-b770-4c6c-b797-565b7b1a423d
  sha: 1a5458bc15acf90eea16353a1dd17285cf97ec35
  size: 804164
nginx/pcre-8.36.tar.gz:
  object_id: 29a019ba-407b-4dfa-9558-480d6e4f80e0
  sha: fb537757756818133d8157ec878bc11f5a93ef4d
  size: 2009464
haproxy/haproxy-1.5.10.tar.gz:
  object_id: 2238d5ca-1b5d-44fa-8170-e4f0a5b6eabe
  sha: 2af3b740e84f10cbd0c90a78c30a222a24fb2945
  size: 1339873
haproxy/pcre-8.36.tar.gz:
  object_id: 14452555-3661-413e-b65b-2d062bb4281e
  sha: fb537757756818133d8157ec878bc11f5a93ef4d
  size: 2009464
rootfs/cflinuxfs2.tar.gz:
  object_id: 53169ec4-47a6-4683-8e05-485d2e29ea51
  sha: 45914689d88484f7ad4efc6a75b9877f48837da4
  size: 249225633
golang/go1.4.2.linux-amd64.tar.gz:
  object_id: bfaf73b1-de68-4c94-9a02-555245b2eb8d
  sha: 5020af94b52b65cc9b6f11d50a67e4bae07b0aff
  size: 62442704
consul/consul_0.5.0_linux_amd64.zip:
  object_id: 3e6c1e47-95a5-45ef-aeec-2cb4cc4c529a
  sha: 00e4c6e9ff2fb326d3b586fd86c3037f3b7e0974
  size: 4669655
java-buildpack/java-buildpack-offline-v3.0.zip:
  object_id: 8fe6e89a-aa63-4119-8fd0-23715820f31d
  sha: a300c3fca530dc16345dbd6feb26b13897d05265
  size: 324816174
java-buildpack/java-buildpack-v3.0.zip:
  object_id: 34bff29b-9ec3-42aa-891f-db301f7f978d
  sha: 177715b012505051d14611bf706f0ebe50cc55f0
  size: 150091
ruby-2.1.6/bundler-1.9.4.gem:
  object_id: 567b4de7-54cd-473e-870a-680ab5d6632c
  sha: ea3f17a76a8249049b5589c9b5421af72189babc
  size: 244224
ruby-2.1.6/ruby-2.1.6.tar.gz:
  object_id: 97c9a690-a164-42c4-8755-6af2f114845b
  sha: 426289b6647ce35ad101091825b6e7e5fce207f3
  size: 15141710
ruby-2.1.6/rubygems-2.4.6.tgz:
  object_id: 250b97aa-7419-4982-ab5f-8cd45f2a6857
  sha: bf59306c0f6c37551875e70ce8ccfb1cbc60c28b
  size: 447588
ruby-2.1.6/yaml-0.1.6.tar.gz:
  object_id: 9b62536a-3cae-416d-a243-78e97b41e346
  sha: f3d404e11bec3c4efcddfd14c42d46f1aabe0b5d
  size: 503012
php-buildpack/php_buildpack-cached-v3.2.2.zip:
  object_id: 4cbd86d2-a739-4a13-90f1-58f6097e718a
  sha: 3a6e7a88754029e6efbaa0d6905fca6086bb0b64
  size: 846464023
go-buildpack/go_buildpack-cached-v1.3.1.zip:
  object_id: 5e671c4a-4b81-41fe-a4a7-9bb6cabe933a
  sha: 82d19816c39e0e77b25ce599117fa07b2e06efe8
  size: 463782558
binary-buildpack/binary_buildpack-cached-v1.0.0.zip:
  object_id: 291a8b75-c692-4b93-8079-ceb930b23c10
  sha: 93636f4aa1b7cf7f063fac135c6691c6dcd7a2d0
  size: 8405
consul/consul-template_0.9.0_linux_amd64.tar.gz:
  object_id: e83bcdcd-2f31-4b73-8cf8-516d54e8f59a
  sha: a44e441f9347abe64956e5bb30c4d4b0464d1f73
  size: 2460384
uaa/newrelic.jar:
  object_id: 2b9d1b59-bc86-4089-95ba-2c0374fe3737
  sha: a5070963fc84bea27acc1d492cb9e3143f0c4715
  size: 7064901
uaa/apache-tomcat-7.0.61.tar.gz:
  object_id: fdad7b89-61f5-4cd1-a003-49c4d872412b
  sha: 98ccbc95d029291e81bf818879ec8a0aa14465df
  size: 8816567
openjdk/openjdk-1.7.0_79.tar.gz:
  object_id: b7c40a5c-6297-4158-b54a-23f89982f13a
  sha: 2ca6e142325a3e054efbf5b72995cb9ce416d607
  size: 36244117
openjdk/openjdk-1.7.0-u40-unofficial-macosx-x86_64-bundle.tgz:
  object_id: 6f065666-1889-4564-8dd9-8344b4a3e974
  sha: ac7febc5bbff2dedf8add624a727a4c0ac6c3d10
  size: 65991397
openjdk/openjdk-1.7.0-u40-unofficial-linux-amd64.tgz:
  object_id: 1c5d266f-9c90-4160-9fc5-b3b30f2c248a
  sha: bb41c68e0dc26ad71635d4bff8da16246ded10f0
  size: 42574624
ruby-buildpack/ruby_buildpack-cached-v1.4.2.zip:
  object_id: 9affa18e-acc3-424e-b264-73483792d0cb
  sha: 08d3ceedc59229eb78fefa09f9e8ed39f0ae79cc
  size: 382942164
postgres/postgresql-9.4.2.tar.gz:
  object_id: 4d807bf7-94bc-449f-a0c3-549642df3085
  sha: 7a70474f9b44fea1b345e48bd5e4418bccf41f3f
  size: 23092865
staticfile-buildpack/staticfile_buildpack-cached-v1.1.0.zip:
  object_id: a449f533-f9a9-4680-bb65-bb5fb1c607bd
  sha: fe8e6bed345a88c387424dc47c213cc13345fcf4
  size: 4684378
nodejs-buildpack/nodejs_buildpack-cached-v1.3.4.zip:
  object_id: c6a02aaf-b917-4102-b243-1ffff9796dbc
  sha: 7ad1ca449292596ba58b4a2f37ef9a5c404b558e
  size: 73107547
python-buildpack/python_buildpack-cached-v1.3.5.zip:
  object_id: 4546ee42-3240-487e-a05a-0936e2fd9f00
  sha: 6245126aff2ef88fd05edbb12a94610f16e67f87
  size: 449080634
rtr/rtr-linux-amd64.tgz:
  object_id: 9ff89e27-0326-498e-bd04-6010e941f039
  sha: cf58eb5f92211d57f282c264dea2b1ad2d5213dd
  size: 2189778
