---
debian_nfs_server/nfs-kernel-server_1%3a1.2.0-4ubuntu4.1_amd64.deb:
  object_id: rest/objects/4e4e78bca41e122204e4e9863d076304f307136db190
  sha: a44b3f8319984bace61f21bb6d15cee1419e5bf3
  size: 169618
uaa/cloudfoundry-identity-varz-1.0.2.war:
  object_id: rest/objects/4e4e78bca21e121204e4e86ee151bc050928ba58f527
  sha: 8c35ed35fb6dfc4a97a243447763c635812066e8
  size: 5727747
nginx/headers-more-v0.25.tgz:
  object_id: a621718d-df24-4205-ba31-6ed8a212732e
  sha: 514bc3df30b24eb0a06533f1ebaa579b898990f5
  size: 27973
nginx/nginx-upload-module-2.2.tar.gz:
  object_id: 502854f1-9823-468f-baef-1a8d68823ead
  sha: 74ccd116525a155db76f92a1cd484d9516a70398
  size: 28505
nginx/newrelic_nginx_agent.tar.gz:
  object_id: cad4fada-4a11-4b1a-a884-c6f58dacead9
  sha: 98a1b10475371705932fea4769f8ac1b0451106f
  size: 5222
cli/cf-linux-amd64.tgz:
  object_id: d491f12d-a877-4d6f-b304-9c93adcd9ff1
  sha: 1c3cdd94c23c2d72a40d8964167e07216679de0f
  size: 5080879
golang/go1.4.3.linux-amd64.tar.gz:
  object_id: 17b23a63-49af-467c-8893-db57a059d7b3
  sha: 332b64236d30a8805fc8dd8b3a269915b4c507fe
  size: 61210288
consul/consul-template_0.9.0_linux_amd64.tar.gz:
  object_id: e83bcdcd-2f31-4b73-8cf8-516d54e8f59a
  sha: a44e441f9347abe64956e5bb30c4d4b0464d1f73
  size: 2460384
uaa/newrelic.jar:
  object_id: 2b9d1b59-bc86-4089-95ba-2c0374fe3737
  sha: a5070963fc84bea27acc1d492cb9e3143f0c4715
  size: 7064901
uaa/apache-tomcat-7.0.61.tar.gz:
  object_id: fdad7b89-61f5-4cd1-a003-49c4d872412b
  sha: 98ccbc95d029291e81bf818879ec8a0aa14465df
  size: 8816567
rtr/rtr-linux-amd64.tgz:
  object_id: 506e3344-e5e8-4576-8e6e-ccd9c33b7f58
  sha: d98c42cbd73c59852d6252b0fd15440d7471a821
  size: 2199020
consul/consul_0.5.2_linux_amd64.zip:
  object_id: 74107b66-7502-4e06-bdc2-d2dbea1e73c6
  sha: b3ae610c670fc3b81737d44724ebde969da66ebf
  size: 4803609
binary-buildpack/binary_buildpack-cached-v1.0.1.zip:
  object_id: ada385dd-f0b6-43c7-8429-0057766116cc
  sha: 3e62e3882495cf16686078e7209bf28d3f9d60f5
  size: 8487
haproxy/haproxy-1.5.14.tar.gz:
  object_id: 02657a44-3292-4e0b-8b18-bcad061a2381
  sha: 159f5beb8fdc6b8059ae51b53dc935d91c0fb51f
  size: 1345345
haproxy/pcre-8.37.tar.gz:
  object_id: 22601a5f-4ef4-4621-80aa-0fa1f8067db6
  sha: 4a24a20c61347d8da4edc86d5475aaf70ac146bb
  size: 2041593
nginx/pcre-8.37.tar.gz:
  object_id: 262a1857-da10-4680-b148-52d7803af7ae
  sha: 4a24a20c61347d8da4edc86d5475aaf70ac146bb
  size: 2041593
nginx/nginx-1.8.0.tar.gz:
  object_id: 0d18bbee-b79d-4fec-bba5-635821969fa0
  sha: 12bad312764feae50246685ab2e74512d1aa9b2f
  size: 832104
mysqlclient-5.5/libmysqlclient-dev_5.5.44.tar.gz:
  object_id: 31e64230-f356-4522-86d6-413a531996b9
  sha: f6cc741b64084752478009505113a39192d89da9
  size: 1376537
ruby-2.2.4/bundler-1.10.6.gem:
  object_id: 74aa8a43-e1f6-43d5-b90d-e86a01b2e404
  sha: 55a37fccd1c0cb5542d468e35d3be46dd0667f73
  size: 251392
ruby-2.2.4/ruby-2.2.4.tar.gz:
  object_id: bb355996-b778-4c98-939c-9716c81f03cd
  sha: 818e5e157f76d4912ba3a7c7b4fc5156105e83c3
  size: 16638151
ruby-2.2.4/rubygems-2.4.8.tgz:
  object_id: 998e4fd8-fd28-4b7d-8870-5394c26e8303
  sha: 0db6b2f1cdd2267fe19f1f875057c2f2ce9f5696
  size: 447712
uaa/cloudfoundry-identity-statsd-1.0.0.war:
  object_id: 03f0688e-c6f3-4a27-8d5c-694b4dda0907
  sha: 038c11e503bdbc5194c76535b22f5d4b85aeb37f
  size: 11163261
postgres/postgresql-9.4.5.tar.gz:
  object_id: 49b445bd-ecd9-483c-bbf0-0965b5900c22
  sha: 5278d04093f3cb2e00796fae15b2e33406844d01
  size: 23211720
openjdk/openjdk-1.8.0_65-x86_64-mountainlion.tar.gz:
  object_id: af9d49da-273e-4b1f-acb7-53d828ff6d7f
  sha: 0d0fef95aa7bdd494f8aac2fa4d94f84b2b3ee9d
  size: 81922523
openjdk/openjdk-1.8.0_65-x86_64-trusty-jre.tar.gz:
  object_id: 7d781bd3-d5d8-485d-9bc5-252e55094d33
  sha: e5ecfe29a74bca1794eb18de03f2f98495c5cbc0
  size: 77054579
openjdk/openjdk-1.8.0_65-x86_64-trusty.tar.gz:
  object_id: 3a1c2b78-c32c-433c-984f-1c60ead8b797
  sha: 949812223e334ba6c360a097a44084776eaee418
  size: 77611856
golang/go1.5.1.linux-amd64.tar.gz:
  object_id: f0f393e9-497b-43b7-b7f0-d5cfdb27ffcd
  sha: 46eecd290d8803887dec718c691cc243f2175fe0
  size: 77875767
nodejs-buildpack/nodejs_buildpack-cached-v1.5.4.zip:
  object_id: 8f0b19f1-5268-489b-b4b2-989fa32f1da9
  sha: 4c3d273d4bdf966b701b46deca622dd9925969f3
  size: 59441206
go-buildpack/go_buildpack-cached-v1.7.1.zip:
  object_id: 43e8d4de-4e92-4384-a27b-006deb701e90
  sha: 04315a6343c182db8d96645a70bb343ad5413ed4
  size: 359292037
java-buildpack/java-buildpack-offline-v3.4.zip:
  object_id: a3457152-674f-409c-b9f3-94a3f44c6f43
  sha: 0184bd894e4e865ac2d7890fdcbce52bdf746852
  size: 251542946
java-buildpack/java-buildpack-v3.4.zip:
  object_id: 457291d7-2e5c-4088-a7f2-3e31b3786220
  sha: 76d93233198aae944b95d2c4a1e1349f1e281d5f
  size: 159423
php-buildpack/php_buildpack-cached-v4.3.2.zip:
  object_id: 467b434d-6026-44c7-99cc-6e5e366e57c2
  sha: fd8f8bedd3b9c14d6360c94c5d7aff5f7f840b9b
  size: 340664447
staticfile-buildpack/staticfile_buildpack-cached-v1.3.0.zip:
  object_id: 8b326d57-6edd-470c-9535-abe10ffe5323
  sha: 89cc3de315dfeb05532a88ba928bb40eaf8a4c58
  size: 2532050
ruby-buildpack/ruby_buildpack-cached-v1.6.12.zip:
  object_id: 7a4cf997-0c4f-460e-819b-024fb7f587c0
  sha: 754a93e6d57b7443d25e03f8862af7be481a42e7
  size: 282145848
ruby-2.1.8/bundler-1.9.4.gem:
  object_id: 25f8ce04-957f-4e17-acd2-f9825a87d132
  sha: ea3f17a76a8249049b5589c9b5421af72189babc
  size: 244224
ruby-2.1.8/ruby-2.1.8.tar.gz:
  object_id: 6e90c843-f647-4f85-80f2-769cd3688258
  sha: c7e50159357afd87b13dc5eaf4ac486a70011149
  size: 15154017
ruby-2.1.8/yaml-0.1.6.tar.gz:
  object_id: 63b9ac28-38d6-4698-bd99-908f80e90405
  sha: f3d404e11bec3c4efcddfd14c42d46f1aabe0b5d
  size: 503012
python-buildpack/python_buildpack-cached-v1.5.4.zip:
  object_id: d41bc9e8-4daf-4681-bb96-71a91125c025
  sha: d77d7634925ecb6bb5130bf659dfb7a4f44a1054
  size: 266308206
rootfs/cflinuxfs2-1.28.0.tar.gz:
  object_id: c62c5ba2-e864-42af-b8b3-b0668d314fc9
  sha: 96ff662b9e03ce460dca71ab547ad41e42fd0c62
  size: 258441667
