---
postgres/postgres-9.0.3-1.amd64.tar.gz:
  object_id: rest/objects/4e4e78bca31e122004e4e8ec646e2104f306af917d30
  sha: e47ee9c841ecde4df121f44df282aeb3c50a48d2
  size: 16203511
postgres/postgres-9.0.3-1.i386.tar.gz:
  object_id: rest/objects/4e4e78bca21e121004e4e7d511f55304f306b0371f99
  sha: b2bde31e720eb219bfdc9f1b784f985ecca2cbfb
  size: 15111387
postgres/postgresql-9.0.3.tar.gz:
  object_id: rest/objects/4e4e78bca21e122004e4e8ec647a5404f306b0ec246e
  sha: c8fb5d1d7930e78211e554bb5751183a8148d0ee
  size: 18335858
debian_nfs_server/nfs-kernel-server_1%3a1.2.0-4ubuntu4.1_amd64.deb:
  object_id: rest/objects/4e4e78bca41e122204e4e9863d076304f307136db190
  sha: a44b3f8319984bace61f21bb6d15cee1419e5bf3
  size: 169618
mysql/client-5.1.62-rel13.3-435-Linux-x86_64.tar.gz:
  object_id: rest/objects/4e4e78bca21e122204e4e9863926b104fb68b259c9fc
  sha: 6e5a17195831688a5f14f20aa5d9cd5d5f4164db
  size: 4105211
uaa/cloudfoundry-identity-varz-1.0.2.war:
  object_id: rest/objects/4e4e78bca21e121204e4e86ee151bc050928ba58f527
  sha: 8c35ed35fb6dfc4a97a243447763c635812066e8
  size: 5727747
nginx/headers-more-v0.25.tgz:
  object_id: a621718d-df24-4205-ba31-6ed8a212732e
  sha: 514bc3df30b24eb0a06533f1ebaa579b898990f5
  size: 27973
nginx/nginx-upload-module-2.2.tar.gz:
  object_id: 502854f1-9823-468f-baef-1a8d68823ead
  sha: 74ccd116525a155db76f92a1cd484d9516a70398
  size: 28505
nginx/newrelic_nginx_agent.tar.gz:
  object_id: cad4fada-4a11-4b1a-a884-c6f58dacead9
  sha: 98a1b10475371705932fea4769f8ac1b0451106f
  size: 5222
uaa/openjdk-1.7.0_51.tar.gz:
  object_id: 67b767f3-4032-4970-8535-05dbf7c696a5
  sha: 0f4d3705e3a4e1452250def57cfc36ab6cc37355
  size: 34729532
uaa/openjdk-1.7.0-u40-unofficial-linux-amd64.tgz:
  object_id: 869c365a-7c65-4454-8c09-212d01fa0fb1
  sha: bb41c68e0dc26ad71635d4bff8da16246ded10f0
  size: 42574624
uaa/openjdk-1.7.0-u40-unofficial-macosx-x86_64-bundle.tgz:
  object_id: 4cfb77f4-ea89-4d3d-85ad-2d0f3d84e676
  sha: ac7febc5bbff2dedf8add624a727a4c0ac6c3d10
  size: 65991397
cli/cf-linux-amd64.tgz:
  object_id: d491f12d-a877-4d6f-b304-9c93adcd9ff1
  sha: 1c3cdd94c23c2d72a40d8964167e07216679de0f
  size: 5080879
golang/go1.3.1.linux-amd64.tar.gz:
  object_id: b4778c9a-1994-4dda-b7a2-97ae93e1b835
  sha: 3af011cc19b21c7180f2604fd85fbc4ddde97143
  size: 51930765
golang/go1.4.2.linux-amd64.tar.gz:
  object_id: bfaf73b1-de68-4c94-9a02-555245b2eb8d
  sha: 5020af94b52b65cc9b6f11d50a67e4bae07b0aff
  size: 62442704
consul/consul-template_0.9.0_linux_amd64.tar.gz:
  object_id: e83bcdcd-2f31-4b73-8cf8-516d54e8f59a
  sha: a44e441f9347abe64956e5bb30c4d4b0464d1f73
  size: 2460384
uaa/newrelic.jar:
  object_id: 2b9d1b59-bc86-4089-95ba-2c0374fe3737
  sha: a5070963fc84bea27acc1d492cb9e3143f0c4715
  size: 7064901
uaa/apache-tomcat-7.0.61.tar.gz:
  object_id: fdad7b89-61f5-4cd1-a003-49c4d872412b
  sha: 98ccbc95d029291e81bf818879ec8a0aa14465df
  size: 8816567
postgres/postgresql-9.4.2.tar.gz:
  object_id: 4d807bf7-94bc-449f-a0c3-549642df3085
  sha: 7a70474f9b44fea1b345e48bd5e4418bccf41f3f
  size: 23092865
rtr/rtr-linux-amd64.tgz:
  object_id: 1d8492e6-ae3d-4411-9bc6-e45d1dc4f99c
  sha: 191e7d6f63ff1dd390e0ab11ec612317f99efb35
  size: 2192159
consul/consul_0.5.2_linux_amd64.zip:
  object_id: 74107b66-7502-4e06-bdc2-d2dbea1e73c6
  sha: b3ae610c670fc3b81737d44724ebde969da66ebf
  size: 4803609
binary-buildpack/binary_buildpack-cached-v1.0.1.zip:
  object_id: ada385dd-f0b6-43c7-8429-0057766116cc
  sha: 3e62e3882495cf16686078e7209bf28d3f9d60f5
  size: 8487
haproxy/haproxy-1.5.14.tar.gz:
  object_id: 02657a44-3292-4e0b-8b18-bcad061a2381
  sha: 159f5beb8fdc6b8059ae51b53dc935d91c0fb51f
  size: 1345345
haproxy/pcre-8.37.tar.gz:
  object_id: 22601a5f-4ef4-4621-80aa-0fa1f8067db6
  sha: 4a24a20c61347d8da4edc86d5475aaf70ac146bb
  size: 2041593
nginx/pcre-8.37.tar.gz:
  object_id: 262a1857-da10-4680-b148-52d7803af7ae
  sha: 4a24a20c61347d8da4edc86d5475aaf70ac146bb
  size: 2041593
staticfile-buildpack/staticfile_buildpack-cached-v1.2.1.zip:
  object_id: 0eebcec7-4850-41d7-b626-a0ef71b221c3
  sha: 4374d3e85ccca8cf086b52e7d2d08cab24689620
  size: 2491340
nodejs-buildpack/nodejs_buildpack-cached-v1.5.0.zip:
  object_id: 56f5eac1-2449-4e95-a570-8311d40164f7
  sha: 366596bd85b21ca3602b68a0401fca8cfa6217cd
  size: 40771189
python-buildpack/python_buildpack-cached-v1.5.0.zip:
  object_id: 1a4956c8-c4b1-4361-ac8b-3ccbb8b93dcb
  sha: 074b9804d66d103acccd7b3be2f711f1171deb56
  size: 184315882
php-buildpack/php_buildpack-cached-v4.0.0.zip:
  object_id: 84cad3aa-3417-48b6-8e13-70fbc5e6833a
  sha: 1dd1942d2d1d4a8ea121f7bec90cac9357d06675
  size: 471190774
java-buildpack/java-buildpack-offline-v3.1.1.zip:
  object_id: d5604cb2-c0fe-431e-b2fd-3e868e2b934c
  sha: db5f96ce966e02c611da8222d4345d420da63655
  size: 333418361
java-buildpack/java-buildpack-v3.1.1.zip:
  object_id: 8e1d1974-a796-4a1b-bc17-ed9ebadbaebc
  sha: 8a0d6e7a1ed26a24abc2a1c7a0b2612d6efd0380
  size: 146570
openjdk/openjdk-1.8.0_51.tar.gz:
  object_id: d85dd2e6-cb0c-45a7-a089-b24a778878ad
  sha: 2651c262b7cede077da23e00d3fe6ffd9849a1d6
  size: 44707537
openjdk/openjdk-1.8.0_51-x86_64-mountainlion.tar.gz:
  object_id: dfb85520-0fcc-4ca1-bcb6-4dafb877fc9a
  sha: 1d6fa87aca3599c15b07a7f96e77db4e0d45fa20
  size: 81845477
openjdk/openjdk-1.8.0_51-x86_64-trusty.tar.gz:
  object_id: d5310553-5f23-4a34-8bbe-6cca4a2a66f5
  sha: f467dc147e1774f9b4bf78aeca65d096d135e7b6
  size: 77486128
ruby-2.1.7/bundler-1.9.4.gem:
  object_id: e158e651-c3ff-4dd0-8f42-f7c2f0e08688
  sha: ea3f17a76a8249049b5589c9b5421af72189babc
  size: 244224
ruby-2.1.7/ruby-2.1.7.tar.gz:
  object_id: 5af4b5ce-4e20-4e26-bda2-c942cb078e38
  sha: e2e195a4a58133e3ad33b955c829bb536fa3c075
  size: 15151458
ruby-2.1.7/yaml-0.1.6.tar.gz:
  object_id: 222e4627-f3f5-4c83-aae6-3c6460aae248
  sha: f3d404e11bec3c4efcddfd14c42d46f1aabe0b5d
  size: 503012
go-buildpack/go_buildpack-cached-v1.6.0.zip:
  object_id: 26010bac-2c0c-43d5-ba41-494cdd54704d
  sha: 191c06d332f76443a45519cdfd3634c6b95cbd1f
  size: 437981507
ruby-buildpack/ruby_buildpack-cached-v1.6.5.zip:
  object_id: d8af5cc5-6f7f-49ba-a360-a3facf57324c
  sha: 2139fd9d376dac991c924f906b393db8226b4b14
  size: 294181987
rootfs/cflinuxfs2-1.7.0.tar.gz:
  object_id: d3aa567b-e5c6-4059-b9a4-b7f6d7876882
  sha: 59a5bdc28a966d04738f60c5477f5e6a5ad2b86b
  size: 248294083
nginx/nginx-1.8.0.tar.gz:
  object_id: 0d18bbee-b79d-4fec-bba5-635821969fa0
  sha: 12bad312764feae50246685ab2e74512d1aa9b2f
  size: 832104
