---
debian_nfs_server/nfs-kernel-server_1%3a1.2.0-4ubuntu4.1_amd64.deb:
  object_id: rest/objects/4e4e78bca41e122204e4e9863d076304f307136db190
  sha: a44b3f8319984bace61f21bb6d15cee1419e5bf3
  size: 169618
uaa/cloudfoundry-identity-varz-1.0.2.war:
  object_id: rest/objects/4e4e78bca21e121204e4e86ee151bc050928ba58f527
  sha: 8c35ed35fb6dfc4a97a243447763c635812066e8
  size: 5727747
nginx/nginx-upload-module-2.2.tar.gz:
  object_id: 502854f1-9823-468f-baef-1a8d68823ead
  sha: 74ccd116525a155db76f92a1cd484d9516a70398
  size: 28505
uaa/newrelic.jar:
  object_id: 2b9d1b59-bc86-4089-95ba-2c0374fe3737
  sha: a5070963fc84bea27acc1d492cb9e3143f0c4715
  size: 7064901
haproxy/haproxy-1.5.14.tar.gz:
  object_id: 02657a44-3292-4e0b-8b18-bcad061a2381
  sha: 159f5beb8fdc6b8059ae51b53dc935d91c0fb51f
  size: 1345345
uaa/cloudfoundry-identity-statsd-1.0.0.war:
  object_id: 03f0688e-c6f3-4a27-8d5c-694b4dda0907
  sha: 038c11e503bdbc5194c76535b22f5d4b85aeb37f
  size: 11163261
ruby-2.1.8/bundler-1.9.4.gem:
  object_id: 25f8ce04-957f-4e17-acd2-f9825a87d132
  sha: ea3f17a76a8249049b5589c9b5421af72189babc
  size: 244224
ruby-2.1.8/ruby-2.1.8.tar.gz:
  object_id: 6e90c843-f647-4f85-80f2-769cd3688258
  sha: c7e50159357afd87b13dc5eaf4ac486a70011149
  size: 15154017
ruby-2.1.8/yaml-0.1.6.tar.gz:
  object_id: 63b9ac28-38d6-4698-bd99-908f80e90405
  sha: f3d404e11bec3c4efcddfd14c42d46f1aabe0b5d
  size: 503012
libmariadb/libmariadb-5.5.36.tar.xz:
  object_id: 4d6e5c2c-76be-4df0-9fdd-4eea3b3563a2
  sha: 4985fd30ffd60de12770153346b4485cd5dcb7ad
  size: 1260684
nginx/newrelic_nginx_agent-1.2.1.tar.gz:
  object_id: c1534fd2-f0f4-4f64-be14-49de4e450173
  sha: 98a1b10475371705932fea4769f8ac1b0451106f
  size: 5222
ruby-2.2.5/ruby-2.2.5.tar.gz:
  object_id: 9a7262fc-f0af-4bba-be5d-b9d59044071a
  sha: 457707459827bd527347a5cee7b4dc509b486713
  size: 16654395
ruby-2.2.5/bundler-1.11.2.gem:
  object_id: 61e0839e-176e-41a1-a13b-ee53337794a3
  sha: 8eb956dec72da753d3d2a2126c78508b17af434e
  size: 263168
ruby-2.2.5/yaml-0.1.6.tar.gz:
  object_id: 1d7ec354-5aa6-4e19-b6e5-51f6d6327814
  sha: f3d404e11bec3c4efcddfd14c42d46f1aabe0b5d
  size: 503012
consul/consul-template_0.14.0_linux_amd64.zip:
  object_id: 498b302c-a737-4036-8cc7-14a64493338d
  sha: f932301f69a477253e4e4bf3c60159ea77cf28a8
  size: 3523492
nginx/nginx-1.11.1.tar.gz:
  object_id: ced13588-cd45-44d4-bf76-0f6d668522ea
  sha: 6b6172b26628b95c4ad0d6cb5b11eb4aa59c2a83
  size: 913417
nginx/headers-more-nginx-module-0.30.tar.gz:
  object_id: e8f3c630-e139-46b4-9363-c178f444edca
  sha: a188a399f3e365a0831585a9d7aa0e6ed1a75f0d
  size: 27793
nginx/pcre-8.39.tar.gz:
  object_id: 70c7bafb-4013-4f07-8287-bfb07faa1085
  sha: b3aec1f643d9701841e2f9d57ac121a7ff448fc8
  size: 2062258
golang/go1.6.3.linux-amd64.tar.gz:
  object_id: 7ad4929c-a987-4b84-b686-3c9598951f25
  sha: 5e916ba4dd8c2fc43beafca4c08b334c4d0686f3
  size: 84856920
postgres/postgresql-9.4.9.tar.gz:
  object_id: 528861b6-d7c1-4ecd-82b1-d9d56aea62ea
  sha: c9d641eb69885672e5aacee413cd778d88b8420d
  size: 23300245
openjdk/openjdk-1.8.0_101-x86_64-trusty.tar.gz:
  object_id: af292af2-8e47-487a-8dfd-c7fd0c04caec
  sha: d77ee059e289ae52fb87812f1a2932268427dc26
  size: 77696717
openjdk/openjdk-1.8.0_101-x86_64-mountainlion.tar.gz:
  object_id: c3dab272-8db3-4bd2-8836-f06e63640a9e
  sha: d9374652844bfd7bcdce8f8b605fb57fd76c9e36
  size: 75550921
cli/cf-cli_6.21.1_linux_x86-64.tgz:
  object_id: 0f4e5011-23d3-4eab-90bd-d6dd5b46c67d
  sha: 7dc397d2a0d93887ef50bc1f852beb686563049e
  size: 6543090
haproxy/pcre-8.39.tar.gz:
  object_id: 0aab6e30-25b2-4844-90be-997feb090e3a
  sha: b3aec1f643d9701841e2f9d57ac121a7ff448fc8
  size: 2062258
binary-buildpack/binary_buildpack-cached-v1.0.5.zip:
  object_id: b321c617-23a3-4e2b-af63-29d60a1d8fcf
  sha: fe0edb11bcc5d42570f10ff9fe97f0c1b94900d1
  size: 9571
java-buildpack/java-buildpack-v3.10.zip:
  object_id: f5efc2ab-ae9e-4ef0-9df2-46188b5e4809
  sha: ae12d21d29ec2a4ceeaf597dc43f11c52a44cc78
  size: 174486
java-buildpack/java-buildpack-offline-v3.10.zip:
  object_id: 660d2edf-3a0e-43f3-80c3-888652b298a8
  sha: aa0816fa7a6e6cb58648ff6fd76d14e4ddab0954
  size: 261228676
etcd/etcd-v2.1.1-linux-amd64.tar.gz:
  object_id: ce50df26-f04b-496a-9ac4-32228020df6a
  sha: d90a29e051f8dea2f5bb4200610ccbcec45497d7
  size: 5608238
php-buildpack/php_buildpack-cached-v4.3.22.zip:
  object_id: 64eb0c22-49ee-4568-8a07-68e1450cdea1
  sha: f13a0a5222bf95d627cce6b9cfd1d2652924c504
  size: 325501311
ruby-buildpack/ruby_buildpack-cached-v1.6.28.zip:
  object_id: 9bb24c8d-e367-4601-9e78-142307a2f932
  sha: 8a661464f13467784bb7adb695f57c43e9ff0bd3
  size: 273491266
nodejs-buildpack/nodejs_buildpack-cached-v1.5.23.zip:
  object_id: c1b2b979-20c7-4710-9971-f5597f9974d8
  sha: 087bd90d92f41ea7431d250df8105df1d4cb74a9
  size: 114740105
python-buildpack/python_buildpack-cached-v1.5.12.zip:
  object_id: 673b0a0e-d5dc-45c3-ad7a-fd9ce9a4e7e8
  sha: eb24b89e2d8230200882e2d17c5fc88fdea910a4
  size: 267714415
staticfile-buildpack/staticfile_buildpack-cached-v1.3.13.zip:
  object_id: 936f1d01-eeaa-446b-91f7-2ae815302307
  sha: 859a7b6964f188dc6face47610c7d95436514457
  size: 2702450
uaa/apache-tomcat-8.0.39.tar.gz:
  object_id: 2166a182-9111-48af-87c5-34cc06f68cac
  sha: 18c54a81e05df39dec9ac02b143875a29b5502d5
  size: 9304967
ruby-2.3/bundler-1.13.6.gem:
  object_id: bad05dd0-86e8-4a45-8a46-70880a1c6dd8
  sha: c4b33f5e0a6ad4a363d2820260f10454197cceff
  size: 307200
ruby-2.3/ruby-2.3.3.tar.gz:
  object_id: 218c9c26-c0b4-4115-84d1-9f0283d6d633
  sha: 1014ee699071aa2ddd501907d18cbe15399c997d
  size: 17813577
ruby-2.3/rubygems-2.6.8.tgz:
  object_id: 2393318f-83ea-4e9c-9d18-83d82ee34d94
  sha: d253fd1caca6103a9e2a69127ac158a3745fbb44
  size: 754300
golang/go1.7.4.linux-amd64.tar.gz:
  size: 84021919
  object_id: 783849db-2186-488f-459f-28d2f22d7b64
  sha: 2e5baf03d1590e048c84d1d5b4b6f2540efaaea1
golang/go1.7.4.windows-amd64.zip:
  size: 90409580
  object_id: dbebd00d-43b7-434d-6603-c7a8fbcbf779
  sha: a0da2f5d67e5b800eba811a34ca4b2aa22cca678
consul/consul_0.7.1_linux_amd64.zip:
  object_id: 08ad90a5-10ab-48cb-bebe-ead924e9ef32
  sha: c2be9eebc40bf552e260c7dd31a77cb60474712f
  size: 7359222
consul-windows/consul_0.7.1_windows_amd64.zip:
  object_id: 0c43024e-2d4a-4b97-8cb7-c566d2147e80
  sha: a4e13dcb189e8235ca6c48029638733e12fb9747
  size: 7299930
rootfs/cflinuxfs2-1.94.0.tar.gz:
  object_id: 2fe0e3e0-4961-49e8-a39f-205e46cedc33
  sha: adcc38d42428fbf8f3eb48a8f6a034bb09ce64fe
  size: 356582530
dotnet-core-buildpack/dotnet-core_buildpack-cached-v1.0.6.zip:
  object_id: 42e970aa-6fa3-4084-a69d-385dc432e21c
  sha: 1cc8547aa27ff33b4d507aeae74bcc282a111091
  size: 177669127
go-buildpack/go_buildpack-cached-v1.7.16.zip:
  object_id: 4751b160-2492-4d17-9d61-627a82aae0bf
  sha: c3cd1775095adfa6d20bd532b3ead8f50bba93d2
  size: 411037160
